(function(){
'use strict';
var app=document.getElementById('app');
var boot=document.getElementById('boot');
var SESSION_KEY='pakkom_v9_student';
var state={classId:'',student:null,exams:[],currentExam:null};
var classList=[];
var adminStudents=[];

function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c];});}
function el(id){return document.getElementById(id);}
function https(u){return /^https:\/\//i.test(String(u||''));}
function hideBoot(){if(boot)boot.classList.add('hide');}
function fatal(msg){if(window.PAKKOM_BOOT_ERROR)window.PAKKOM_BOOT_ERROR(msg);}
function fmt(ts){try{var d=ts&&typeof ts.toDate==='function'?ts.toDate():(ts instanceof Date?ts:null);return d?d.toLocaleString('id-ID'):'-';}catch(e){return '-';}}
function top(title,body,backFn,backText){app.innerHTML='<div class="top"><div class="brand"><span class="logo">P</span><b>'+esc(title)+'</b></div><button class="btn gray small" id="topBack">'+esc(backText||'Kembali')+'</button></div>'+body;var b=el('topBack');if(b)b.onclick=backFn||home;}
function setMsg(id,msg,type){var n=el(id);if(n)n.innerHTML='<span class="'+(type||'error')+'">'+esc(msg)+'</span>';}

if(typeof firebase==='undefined'){fatal('Firebase tidak berhasil dimuat. Periksa koneksi internet lalu muat ulang halaman.');return;}
if(!window.FIREBASE_CONFIG){fatal('FIREBASE_CONFIG tidak ditemukan di config.js.');return;}
var db,auth;
try{if(!firebase.apps.length)firebase.initializeApp(window.FIREBASE_CONFIG);auth=firebase.auth();db=firebase.firestore();}catch(e){fatal('Konfigurasi Firebase gagal: '+e.message);return;}
hideBoot();

function saveSession(){try{if(state.student)localStorage.setItem(SESSION_KEY,JSON.stringify({id:state.student.id,classId:state.classId}));}catch(e){}}
function clearSession(){try{localStorage.removeItem(SESSION_KEY);}catch(e){}state={classId:'',student:null,exams:[],currentExam:null};}
function restoreSession(done){var raw='';try{raw=localStorage.getItem(SESSION_KEY)||'';}catch(e){}if(!raw){done(false);return;}try{var s=JSON.parse(raw);if(!s.id||!s.classId){done(false);return;}db.collection('students').doc(s.id).get().then(function(d){if(!d.exists){clearSession();done(false);return;}var x=d.data();if(x.active===false||String(x.classId)!==String(s.classId)){clearSession();done(false);return;}state.classId=s.classId;state.student=Object.assign({id:d.id},x);done(true);}).catch(function(){clearSession();done(false);});}catch(e){clearSession();done(false);}}

function home(){restoreSession(function(ok){if(ok){studentDashboard();return;}app.innerHTML='<div class="login card"><div class="hero"><span class="logo">P</span><h1>PakKom Exambro V9</h1><p class="muted">Portal ujian siswa</p></div><div class="grid"><button class="btn" id="studentBtn">Siswa</button><button class="btn gray" id="adminBtn">Admin</button></div><div class="notice"><b>Alur siswa:</b> pilih kelas → password kelas → login/daftar → pilih ujian → PIN.</div><p class="muted smalltext">Jika terjadi masalah, halaman ini akan menampilkan pesan error dan tidak lagi menjadi layar putih.</p></div>';el('studentBtn').onclick=classGate;el('adminBtn').onclick=adminLogin;});}

function loadClasses(cb){db.collection('classes').where('active','==',true).get().then(function(s){classList=s.docs.map(function(d){return Object.assign({id:d.id},d.data());}).sort(function(a,b){return String(a.id).localeCompare(String(b.id),undefined,{numeric:true});});cb();}).catch(function(e){classList=[];cb(e);});}
function classGate(){app.innerHTML='<div class="login card"><h1>Masuk Kelas</h1><label>Kelas</label><select id="kelas"><option value="">Memuat kelas…</option></select><label>Password Kelas</label><input id="kpw" class="input" type="password" placeholder="Password kelas"><button class="btn block" id="classContinue">Lanjut</button><button class="btn gray block" id="classBack" style="margin-top:8px">Kembali</button><div id="classMsg"></div></div>';el('classBack').onclick=home;el('classContinue').onclick=verifyClass;loadClasses(function(err){var s=el('kelas');if(err){s.innerHTML='<option value="">Kelas gagal dimuat</option>';setMsg('classMsg','Data kelas tidak dapat dibaca. Periksa koneksi atau Firestore Rules.','error');return;}s.innerHTML='<option value="">-- Pilih kelas --</option>'+classList.map(function(x){return '<option value="'+esc(x.id)+'">'+esc(x.name||x.id)+'</option>';}).join('');});}
function verifyClass(){var id=el('kelas').value,p=el('kpw').value;if(!id||!p){setMsg('classMsg','Pilih kelas dan masukkan password.');return;}var c=classList.find(function(x){return String(x.id)===String(id);});if(c&&c.active!==false&&String(c.password||c.demoPassword||'')===String(p)){state.classId=id;studentChoice();return;}db.collection('classes').doc(id).get().then(function(d){var x=d.data()||{};if(d.exists&&x.active!==false&&String(x.password||x.demoPassword||'')===String(p)){state.classId=id;studentChoice();}else setMsg('classMsg','Password kelas salah.');}).catch(function(){setMsg('classMsg','Gagal memeriksa kelas. Periksa koneksi atau Rules.');});}
function studentChoice(){app.innerHTML='<div class="login card"><h1>Kelas '+esc(state.classId)+'</h1><p class="muted">Pilih sesuai kondisi siswa.</p><div class="grid"><button class="btn" id="loginBtn">Login Siswa</button><button class="btn green" id="regBtn">Daftar Siswa</button></div><button class="btn gray block" id="changeClass" style="margin-top:10px">Ganti Kelas</button></div>';el('loginBtn').onclick=loginStudent;el('regBtn').onclick=registerStudent;el('changeClass').onclick=classGate;}
function loginStudent(){app.innerHTML='<div class="login card"><h1>Login Siswa</h1><span class="pill">Kelas '+esc(state.classId)+'</span><div class="divider"></div><label>NIS</label><input id="lnis" class="input" inputmode="numeric"><label>Password</label><input id="lpw" class="input" type="password"><button class="btn block" id="doLogin">Masuk</button><button class="btn gray block" id="loginBack" style="margin-top:8px">Kembali</button><div id="loginMsg"></div></div>';el('doLogin').onclick=doStudentLogin;el('loginBack').onclick=studentChoice;}
function doStudentLogin(){var nis=el('lnis').value.trim(),p=el('lpw').value;if(!nis||!p){setMsg('loginMsg','NIS dan password wajib diisi.');return;}setMsg('loginMsg','Memeriksa akun…','info');db.collection('students').where('nis','==',nis).where('classId','==',state.classId).limit(1).get().then(function(q){if(q.empty){setMsg('loginMsg','NIS tidak ditemukan di kelas ini.');return;}var d=q.docs[0],x=d.data();if(x.active===false){setMsg('loginMsg','Akun siswa sedang dinonaktifkan.');return;}if(String(x.password)!==String(p)){setMsg('loginMsg','Password siswa salah.');return;}state.student=Object.assign({id:d.id},x);saveSession();studentDashboard();}).catch(function(){setMsg('loginMsg','Login gagal. Periksa koneksi atau Firestore Rules.');});}
function registerStudent(){app.innerHTML='<div class="login card"><h1>Daftar Siswa</h1><span class="pill">Kelas '+esc(state.classId)+'</span><div class="divider"></div><label>NIS</label><input id="rnis" class="input" inputmode="numeric"><label>Nama Lengkap</label><input id="rname" class="input"><label>Password</label><input id="rpw" class="input" type="password" placeholder="Minimal 6 karakter"><label>Konfirmasi Password</label><input id="rcpw" class="input" type="password"><button class="btn green block" id="doReg">Daftar</button><button class="btn gray block" id="regBack" style="margin-top:8px">Kembali</button><div id="regMsg"></div></div>';el('doReg').onclick=doRegister;el('regBack').onclick=studentChoice;}
function doRegister(){var nis=el('rnis').value.trim(),name=el('rname').value.trim(),p=el('rpw').value,cp=el('rcpw').value;if(!nis||!name||!p){setMsg('regMsg','NIS, nama, dan password wajib diisi.');return;}if(p.length<6){setMsg('regMsg','Password minimal 6 karakter.');return;}if(p!==cp){setMsg('regMsg','Konfirmasi password tidak sama.');return;}setMsg('regMsg','Menyimpan akun…','info');db.collection('students').where('nis','==',nis).limit(1).get().then(function(q){if(!q.empty){setMsg('regMsg','NIS sudah terdaftar.');return;}return db.collection('students').add({nis:nis,name:name,classId:state.classId,password:p,active:true,createdAt:firebase.firestore.FieldValue.serverTimestamp()}).then(function(ref){state.student={id:ref.id,nis:nis,name:name,classId:state.classId,active:true};saveSession();studentDashboard();});}).catch(function(){setMsg('regMsg','Registrasi gagal. Periksa Firestore Rules.');});}

function studentDashboard(){if(!state.student){home();return;}db.collection('examPublic').where('active','==',true).get().then(function(s){var exams=s.docs.map(function(d){return Object.assign({id:d.id},d.data());}).filter(function(x){return !Array.isArray(x.allowedClasses)||!x.allowedClasses.length||x.allowedClasses.indexOf(state.classId)>=0;});state.exams=exams;renderStudentDashboard();}).catch(function(){state.exams=[];renderStudentDashboard('Ujian tidak dapat dimuat. Periksa koneksi atau Rules.');});}
function examStatus(x){var n=Date.now(),st=x.startAt&&typeof x.startAt.toDate==='function'?x.startAt.toDate().getTime():0,en=x.endAt&&typeof x.endAt.toDate==='function'?x.endAt.toDate().getTime():0;if(st&&n<st)return {label:'Belum mulai',disabled:true};if(en&&n>en)return {label:'Berakhir',disabled:true};return {label:'Aktif',disabled:false};}
function renderStudentDashboard(err){var cards=state.exams.map(function(x){var st=examStatus(x);return '<div class="exam"><div class="row"><div><h3>'+esc(x.name||'Ujian')+'</h3><div class="muted">'+esc(x.subject||'Ujian online')+'</div></div><span class="pill '+(st.disabled?'gray':'green')+'">'+st.label+'</span></div>'+(x.description?'<p>'+esc(x.description)+'</p>':'')+'<p class="smalltext muted">'+(x.startAt?'Mulai: '+esc(fmt(x.startAt)):'Tanpa jadwal mulai')+(x.endAt?' • Selesai: '+esc(fmt(x.endAt)):'')+'</p><button class="btn '+(st.disabled?'gray':'')+'" data-exam="'+esc(x.id)+'" '+(st.disabled?'disabled':'')+'>'+ (st.disabled?'Tidak tersedia':'Mulai Ujian') +'</button></div>';}).join('');top('PakKom Exambro','<div class="wrap"><div class="card"><div class="row"><div><span class="pill">Kelas '+esc(state.classId)+'</span><h1 style="margin-top:8px">'+esc(state.student.name)+'</h1><p class="muted">NIS: '+esc(state.student.nis)+'</p></div><button class="btn red small" id="logoutStudent">Keluar</button></div></div><div class="card"><h2>Ujian Tersedia</h2>'+(err?'<div class="error">'+esc(err)+'</div>':'')+(cards||'<div class="empty">Belum ada ujian aktif untuk kelas ini.</div>')+'</div></div>',home,'Beranda');el('logoutStudent').onclick=function(){clearSession();home();};Array.prototype.forEach.call(document.querySelectorAll('[data-exam]'),function(b){b.onclick=function(){examPin(b.getAttribute('data-exam'));};});}
function examPin(id){var x=state.exams.find(function(a){return a.id===id;});if(!x)return studentDashboard();state.currentExam=x;app.innerHTML='<div class="login card"><h1>PIN Ujian</h1><h2>'+esc(x.name)+'</h2><label>Masukkan PIN</label><input id="examPin" class="input" inputmode="numeric"><button class="btn block" id="verifyPinBtn">Buka Ujian</button><button class="btn gray block" id="pinBack" style="margin-top:8px">Kembali</button><div id="pinMsg"></div></div>';el('verifyPinBtn').onclick=function(){verifyPin(id);};el('pinBack').onclick=studentDashboard;}
function verifyPin(id){var p=el('examPin').value.trim();if(!p){setMsg('pinMsg','PIN wajib diisi.');return;}setMsg('pinMsg','Memeriksa PIN…','info');db.collection('examSecrets').doc(id).get().then(function(d){if(!d.exists||String((d.data()||{}).pin)!==String(p)){setMsg('pinMsg','PIN salah.');return;}examReady();}).catch(function(){setMsg('pinMsg','PIN tidak dapat diperiksa. Periksa koneksi atau Rules.');});}
function examReady(){var x=state.currentExam;if(!x)return studentDashboard();app.innerHTML='<div class="login card exam-ready"><span class="pill green">Siap ujian</span><h1>'+esc(x.name)+'</h1><p>'+esc(state.student.name)+' • '+esc(state.student.nis)+'</p><div class="warning-banner">Setelah menekan <b>Mulai Sekarang</b>, jangan tutup halaman sebelum ujian selesai.</div><button class="btn green block" id="startExam">Mulai Sekarang</button><button class="btn gray block" id="readyBack" style="margin-top:8px">Kembali</button><p class="smalltext muted">Web browser tidak dapat mengunci seluruh perangkat seperti aplikasi kiosk/Exambro native.</p></div>';el('startExam').onclick=launchExam;el('readyBack').onclick=studentDashboard;}
function launchExam(){var x=state.currentExam;if(!x||!https(x.url)){alert('Link ujian tidak valid. Link harus menggunakan HTTPS.');return;}try{db.collection('examAttempts').add({examId:x.id,studentId:state.student.id,nis:state.student.nis,name:state.student.name,classId:state.classId,startedAt:firebase.firestore.FieldValue.serverTimestamp()});}catch(e){}try{if(document.documentElement.requestFullscreen)document.documentElement.requestFullscreen();}catch(e){}window.location.href=x.url;}

function adminLogin(){app.innerHTML='<div class="login card"><h1>Login Admin</h1><label>Email</label><input id="adminEmail" class="input" type="email"><label>Password</label><input id="adminPass" class="input" type="password"><button class="btn block" id="doAdmin">Masuk</button><button class="btn gray block" id="adminBack" style="margin-top:8px">Kembali</button><div id="adminMsg"></div></div>';el('doAdmin').onclick=doAdminLogin;el('adminBack').onclick=home;}
function doAdminLogin(){var email=el('adminEmail').value.trim(),pass=el('adminPass').value;if(!email||!pass){setMsg('adminMsg','Email dan password wajib diisi.');return;}setMsg('adminMsg','Memeriksa admin…','info');auth.signInWithEmailAndPassword(email,pass).then(function(c){return db.collection('admins').doc(c.user.uid).get();}).then(function(d){if(!d.exists||d.data().role!=='admin'||d.data().active!==true){auth.signOut();setMsg('adminMsg','Akun ini bukan admin aktif.');return;}admin();}).catch(function(){setMsg('adminMsg','Login admin gagal.');});}
function ensureAdmin(cb){var u=auth.currentUser;if(!u){cb(false);return;}db.collection('admins').doc(u.uid).get().then(function(d){cb(!!(d.exists&&d.data().role==='admin'&&d.data().active===true));}).catch(function(){cb(false);});}
function admin(){ensureAdmin(function(ok){if(!ok){adminLogin();return;}Promise.all([db.collection('classes').get(),db.collection('students').get(),db.collection('examPublic').get()]).then(function(res){top('PakKom Exambro — Admin','<div class="wrap"><div class="card"><div class="row"><div><h1>Dashboard Admin</h1><p class="muted">Kelola kelas, siswa, dan ujian.</p></div><button class="btn red small" id="adminLogout">Keluar</button></div></div><div class="grid"><div class="menu-card card"><h2>'+res[0].size+'</h2><p>Kelas</p><button class="btn block" id="manageClasses">Kelola Kelas</button></div><div class="menu-card card"><h2>'+res[1].size+'</h2><p>Siswa</p><button class="btn block" id="manageStudents">Kelola Siswa</button></div><div class="menu-card card"><h2>'+res[2].size+'</h2><p>Ujian</p><button class="btn block" id="manageExams">Kelola Ujian</button></div></div><div class="notice">Versi ini mempertahankan struktur data V7 agar kompatibel. Untuk produksi skala besar, autentikasi siswa sebaiknya dipindahkan ke backend/Auth yang aman.</div></div>',home,'Beranda');el('adminLogout').onclick=function(){auth.signOut().then(home);};el('manageClasses').onclick=classesAdmin;el('manageStudents').onclick=studentsAdmin;el('manageExams').onclick=examsAdmin;}).catch(function(){alert('Dashboard admin gagal memuat data. Periksa Rules.');});});}
function classesAdmin(){ensureAdmin(function(ok){if(!ok){adminLogin();return;}db.collection('classes').get().then(function(s){var rows=s.docs.sort(function(a,b){return a.id.localeCompare(b.id,undefined,{numeric:true});}).map(function(d){var x=d.data();return '<tr><td><b>'+esc(d.id)+'</b></td><td>'+(x.active===false?'Nonaktif':'Aktif')+'</td><td><div class="actions"><button class="btn gray small class-edit" data-id="'+esc(d.id)+'">Password</button><button class="btn small '+(x.active===false?'green':'orange')+' class-toggle" data-id="'+esc(d.id)+'" data-active="'+(x.active===false?'0':'1')+'">'+(x.active===false?'Aktifkan':'Nonaktifkan')+'</button></div></td></tr>';}).join('');top('Kelola Kelas','<div class="wrap"><div class="card"><h2>Tambah / Perbarui Kelas</h2><label>Kode kelas</label><input id="newClass" class="input" placeholder="7A"><label>Password kelas</label><input id="newClassPass" class="input" type="password" placeholder="Minimal 4 karakter"><button class="btn green" id="saveClass">Simpan</button></div><div class="card"><div class="table-wrap"><table class="table"><tr><th>Kelas</th><th>Status</th><th>Aksi</th></tr>'+rows+'</table></div></div></div>',admin,'Admin');el('saveClass').onclick=saveClass;Array.prototype.forEach.call(document.querySelectorAll('.class-edit'),function(b){b.onclick=function(){editClass(b.dataset.id);};});Array.prototype.forEach.call(document.querySelectorAll('.class-toggle'),function(b){b.onclick=function(){toggleClass(b.dataset.id,b.dataset.active==='1');};});});});}
function saveClass(){var id=el('newClass').value.trim().toUpperCase(),p=el('newClassPass').value;if(!id||p.length<4){alert('Kode kelas dan password minimal 4 karakter wajib diisi.');return;}db.collection('classes').doc(id).set({name:id,password:p,active:true},{merge:true}).then(classesAdmin);}
function editClass(id){var p=prompt('Password kelas baru:');if(p===null)return;if(p.length<4){alert('Password minimal 4 karakter.');return;}db.collection('classes').doc(id).update({password:p}).then(classesAdmin);}
function toggleClass(id,active){db.collection('classes').doc(id).update({active:!active}).then(classesAdmin);}
function studentsAdmin(){ensureAdmin(function(ok){if(!ok){adminLogin();return;}db.collection('students').get().then(function(s){adminStudents=s.docs.map(function(d){return Object.assign({id:d.id},d.data());}).sort(function(a,b){return String(a.name||'').localeCompare(String(b.name||''));});var cls=[];adminStudents.forEach(function(x){if(x.classId&&cls.indexOf(x.classId)<0)cls.push(x.classId);});cls.sort();top('Kelola Siswa','<div class="wrap"><div class="card"><h2>Tambah Siswa Manual</h2><div class="grid"><div><label>NIS</label><input id="anIS" class="input"></div><div><label>Nama</label><input id="anName" class="input"></div><div><label>Kelas</label><input id="anClass" class="input"></div><div><label>Password</label><input id="anPass" class="input" value="123456"></div></div><button class="btn green" id="addStudent">Tambah Siswa</button></div><div class="card"><div class="toolbar"><div><label>Cari</label><input id="studentSearch" class="input" placeholder="NIS atau nama"></div><div><label>Kelas</label><select id="studentFilter"><option value="">Semua</option>'+cls.map(function(c){return '<option>'+esc(c)+'</option>';}).join('')+'</select></div><button class="btn gray" id="exportCsv">Export CSV</button></div><div id="studentTable"></div></div></div>',admin,'Admin');el('addStudent').onclick=addStudentManual;el('studentSearch').oninput=renderStudents;el('studentFilter').onchange=renderStudents;el('exportCsv').onclick=exportStudents;renderStudents();});});}
function renderStudents(){var q=(el('studentSearch')?el('studentSearch').value:'').toLowerCase().trim(),f=el('studentFilter')?el('studentFilter').value:'';var rows=adminStudents.filter(function(x){return (!f||String(x.classId)===f)&&(!q||String(x.nis||'').toLowerCase().indexOf(q)>=0||String(x.name||'').toLowerCase().indexOf(q)>=0);});var html='<p class="muted">'+rows.length+' siswa ditampilkan.</p><div class="table-wrap"><table class="table"><tr><th>NIS</th><th>Nama</th><th>Kelas</th><th>Status</th><th>Aksi</th></tr>'+rows.map(function(x){return '<tr><td>'+esc(x.nis)+'</td><td>'+esc(x.name)+'</td><td>'+esc(x.classId)+'</td><td>'+(x.active===false?'Nonaktif':'Aktif')+'</td><td><div class="actions"><button class="btn gray small student-reset" data-id="'+esc(x.id)+'">Reset Password</button><button class="btn small '+(x.active===false?'green':'orange')+' student-toggle" data-id="'+esc(x.id)+'" data-active="'+(x.active===false?'0':'1')+'">'+(x.active===false?'Aktifkan':'Nonaktifkan')+'</button></div></td></tr>';}).join('')+'</table></div>';el('studentTable').innerHTML=html;Array.prototype.forEach.call(document.querySelectorAll('.student-reset'),function(b){b.onclick=function(){resetStudent(b.dataset.id);};});Array.prototype.forEach.call(document.querySelectorAll('.student-toggle'),function(b){b.onclick=function(){toggleStudent(b.dataset.id,b.dataset.active==='1');};});}
function addStudentManual(){var nis=el('anIS').value.trim(),name=el('anName').value.trim(),cls=el('anClass').value.trim().toUpperCase(),p=el('anPass').value;if(!nis||!name||!cls||p.length<6){alert('Isi NIS, nama, kelas, dan password minimal 6 karakter.');return;}db.collection('students').where('nis','==',nis).limit(1).get().then(function(q){if(!q.empty){alert('NIS sudah terdaftar.');return;}return db.collection('students').add({nis:nis,name:name,classId:cls,password:p,active:true,createdAt:firebase.firestore.FieldValue.serverTimestamp()}).then(studentsAdmin);});}
function resetStudent(id){var p=prompt('Password baru:','123456');if(p===null)return;if(p.length<6){alert('Password minimal 6 karakter.');return;}db.collection('students').doc(id).update({password:p}).then(studentsAdmin);}
function toggleStudent(id,active){db.collection('students').doc(id).update({active:!active}).then(studentsAdmin);}
function exportStudents(){var lines=['NIS,Nama,Kelas,Status'];adminStudents.forEach(function(x){lines.push(csv(x.nis)+','+csv(x.name)+','+csv(x.classId)+','+csv(x.active===false?'Nonaktif':'Aktif'));});var blob=new Blob(['\ufeff'+lines.join('\n')],{type:'text/csv;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='data-siswa-pakkom.csv';a.click();setTimeout(function(){URL.revokeObjectURL(url);},500);}
function csv(v){var s=String(v==null?'':v);return /[",\n]/.test(s)?'"'+s.replace(/"/g,'""')+'"':s;}
function examsAdmin(){ensureAdmin(function(ok){if(!ok){adminLogin();return;}db.collection('examPublic').get().then(function(s){var docs=s.docs;var cards=docs.map(function(d){var x=d.data();return '<div class="exam"><div class="row"><div><h3>'+esc(x.name)+'</h3><div class="muted">'+esc(x.subject||'')+'</div></div><span class="pill '+(x.active===false?'red':'green')+'">'+(x.active===false?'Nonaktif':'Aktif')+'</span></div><p class="smalltext">Kelas: '+esc((x.allowedClasses||[]).join(', ')||'Semua')+'</p><p class="smalltext muted">'+esc(x.url||'')+'</p><div class="actions"><button class="btn small '+(x.active===false?'green':'orange')+' exam-toggle" data-id="'+esc(d.id)+'" data-active="'+(x.active===false?'0':'1')+'">'+(x.active===false?'Aktifkan':'Nonaktifkan')+'</button><button class="btn red small exam-delete" data-id="'+esc(d.id)+'">Hapus</button></div></div>';}).join('');top('Kelola Ujian','<div class="wrap"><div class="card"><h2>Tambah Ujian</h2><label>Nama Ujian</label><input id="examName" class="input"><label>Mata Pelajaran</label><input id="examSubject" class="input"><label>Link Ujian HTTPS</label><input id="examUrl" class="input" placeholder="https://..."><label>Kelas Peserta</label><input id="examClasses" class="input" placeholder="7A,7B atau kosong untuk semua"><label>PIN</label><input id="examSecret" class="input" inputmode="numeric"><div class="grid"><div><label>Mulai</label><input id="examStart" class="input" type="datetime-local"></div><div><label>Selesai</label><input id="examEnd" class="input" type="datetime-local"></div></div><button class="btn green" id="saveExam">Simpan Ujian</button></div><div class="card"><h2>Daftar Ujian</h2>'+(cards||'<div class="empty">Belum ada ujian.</div>')+'</div></div>',admin,'Admin');el('saveExam').onclick=saveExam;Array.prototype.forEach.call(document.querySelectorAll('.exam-toggle'),function(b){b.onclick=function(){toggleExam(b.dataset.id,b.dataset.active==='1');};});Array.prototype.forEach.call(document.querySelectorAll('.exam-delete'),function(b){b.onclick=function(){deleteExam(b.dataset.id);};});});});}
function saveExam(){var name=el('examName').value.trim(),subject=el('examSubject').value.trim(),url=el('examUrl').value.trim(),pin=el('examSecret').value.trim(),classes=el('examClasses').value.split(',').map(function(x){return x.trim().toUpperCase();}).filter(Boolean),st=el('examStart').value,en=el('examEnd').value;if(!name||!https(url)||!pin){alert('Nama, link HTTPS, dan PIN wajib diisi.');return;}if(st&&en&&new Date(en)<=new Date(st)){alert('Waktu selesai harus setelah waktu mulai.');return;}var data={name:name,subject:subject,url:url,allowedClasses:classes,active:true,createdAt:firebase.firestore.FieldValue.serverTimestamp()};if(st)data.startAt=new Date(st);if(en)data.endAt=new Date(en);db.collection('examPublic').add(data).then(function(ref){return db.collection('examSecrets').doc(ref.id).set({pin:pin});}).then(examsAdmin).catch(function(){alert('Ujian gagal disimpan atau PIN tidak dapat ditulis. Periksa Rules.');});}
function toggleExam(id,active){db.collection('examPublic').doc(id).update({active:!active}).then(examsAdmin);}
function deleteExam(id){if(!confirm('Hapus ujian ini?'))return;db.collection('examPublic').doc(id).delete().then(function(){return db.collection('examSecrets').doc(id).delete().catch(function(){});}).then(examsAdmin);}

home();
})();
