(function(){
'use strict';
var app=document.getElementById('app'),boot=document.getElementById('boot');
var SESSION_KEY='pakkom_v12_student_activity';
var ADMIN_KEY='pakkom_v12_admin_activity';
var INACTIVITY_LIMIT=60*60*1000;
var state={classId:'',student:null,exams:[],currentExam:null};
var adminStudents=[];
function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c];});}
function el(id){return document.getElementById(id);} function https(u){return /^https:\/\//i.test(String(u||''));}
function setMsg(id,msg,type){var n=el(id);if(n)n.innerHTML='<span class="'+(type||'error')+'">'+esc(msg)+'</span>';}
function hideBoot(){if(boot)boot.style.display='none';}
function fmt(ts){try{var d=ts&&ts.toDate?ts.toDate():null;return d?d.toLocaleString('id-ID'):'-';}catch(e){return '-';}}
if(typeof firebase==='undefined'||!window.FIREBASE_CONFIG){window.PAKKOM_BOOT_ERROR('Firebase/config.js tidak termuat.');return;}
var auth,db,fn;
try{if(!firebase.apps.length)firebase.initializeApp(window.FIREBASE_CONFIG);auth=firebase.auth();db=firebase.firestore();fn=firebase.app().functions('asia-southeast2');auth.setPersistence(firebase.auth.Auth.Persistence.LOCAL).catch(function(){});}catch(e){window.PAKKOM_BOOT_ERROR(e.message);return;}
hideBoot();
var verifyClassFn=fn.httpsCallable('verifyClass'),registerStudentFn=fn.httpsCallable('registerStudent'),studentLoginFn=fn.httpsCallable('studentLogin'),getStudentSessionFn=fn.httpsCallable('getStudentSession'),endStudentSessionFn=fn.httpsCallable('endStudentSession'),verifyExamPinFn=fn.httpsCallable('verifyExamPin');
function cloudErr(e){return (e&&e.message?e.message.replace(/^.*?:\s*/, ''):'Layanan server gagal.');}
function ensureAnon(cb){var u=auth.currentUser;if(u&&u.isAnonymous){cb();return;}if(u&&!u.isAnonymous){auth.signOut().then(function(){return auth.signInAnonymously();}).then(cb).catch(function(e){alert('Anonymous Authentication belum aktif: '+e.message);});return;}auth.signInAnonymously().then(cb).catch(function(e){alert('Anonymous Authentication belum aktif: '+e.message);});}
function saveActivity(){try{localStorage.setItem(SESSION_KEY,String(Date.now()));}catch(e){}}
function activityExpired(){try{var t=Number(localStorage.getItem(SESSION_KEY)||0);return !t||Date.now()-t>=INACTIVITY_LIMIT;}catch(e){return true;}}
function clearActivity(){try{localStorage.removeItem(SESSION_KEY);}catch(e){}}
function touch(){if(state.student)saveActivity();if(auth.currentUser&&!auth.currentUser.isAnonymous){try{localStorage.setItem(ADMIN_KEY,String(Date.now()));}catch(e){}}}
['click','touchstart','keydown','scroll','pointerdown'].forEach(function(ev){document.addEventListener(ev,touch,{passive:true});});
setInterval(function(){if(state.student&&activityExpired())logoutStudent('Sesi berakhir karena 60 menit tidak ada aktivitas.');if(!state.student&&auth.currentUser&&!auth.currentUser.isAnonymous){var t=0;try{t=Number(localStorage.getItem(ADMIN_KEY)||0);}catch(e){}if(t&&Date.now()-t>=INACTIVITY_LIMIT){auth.signOut().then(function(){renderHome('Sesi admin berakhir karena 60 menit tidak ada aktivitas.');});}}},30000);
function home(message){state={classId:'',student:null,exams:[],currentExam:null};auth.onAuthStateChanged(function(u){if(u&&u.isAnonymous&&!activityExpired()){getStudentSessionFn().then(function(r){if(r.data&&r.data.active){state.student=r.data.student;state.classId=r.data.student.classId;studentDashboard();}else renderHome(message);}).catch(function(){renderHome(message);});}else renderHome(message);});}
function renderHome(message){app.innerHTML='<div class="login card"><div class="hero"><span class="logo">P</span><h1>PakKom Exambro V12</h1><p class="muted">Portal ujian siswa</p></div>'+(message?'<div class="notice">'+esc(message)+'</div>':'')+'<div class="grid"><button class="btn" id="studentBtn">Siswa</button><button class="btn gray" id="adminBtn">Admin</button></div><div class="notice"><b>Alur:</b> kelas → login/daftar → approval → ujian → PIN.</div></div>';el('studentBtn').onclick=function(){ensureAnon(classGate);};el('adminBtn').onclick=adminLogin;}
function classGate(){app.innerHTML='<div class="login card"><h1>Masuk Kelas</h1><label>Kelas</label><select id="kelas">'+classOptions()+'</select><label>Password Kelas</label><input id="kpw" class="input" type="password"><button class="btn block" id="go">Lanjut</button><button class="btn gray block" id="back" style="margin-top:8px">Kembali</button><div id="msg"></div></div>';el('go').onclick=function(){var c=el('kelas').value,p=el('kpw').value;if(!c||!p)return setMsg('msg','Pilih kelas dan masukkan password.');setMsg('msg','Memeriksa kelas…','info');verifyClassFn({classId:c,password:p}).then(function(){state.classId=c;studentChoice();}).catch(function(e){setMsg('msg',cloudErr(e));});};el('back').onclick=function(){renderHome('');};}
function classOptions(){var h='<option value="">-- Pilih kelas --</option>';['7','8','9'].forEach(function(g){'ABCDEFGHI'.split('').forEach(function(l){h+='<option>'+g+l+'</option>';});});return h;}
function studentChoice(){app.innerHTML='<div class="login card"><h1>Kelas '+esc(state.classId)+'</h1><div class="grid"><button class="btn" id="login">Login Siswa</button><button class="btn green" id="reg">Daftar Mandiri</button></div><button class="btn gray block" id="back" style="margin-top:10px">Ganti Kelas</button></div>';el('login').onclick=loginStudent;el('reg').onclick=registerStudent;el('back').onclick=classGate;}
function registerStudent(){app.innerHTML='<div class="login card"><h1>Daftar Siswa</h1><span class="pill">Kelas '+esc(state.classId)+'</span><div class="divider"></div><label>NIS</label><input id="nis" class="input"><label>Nama Lengkap</label><input id="name" class="input"><label>Password</label><input id="pw" class="input" type="password"><label>Konfirmasi Password</label><input id="cpw" class="input" type="password"><button class="btn green block" id="save">Daftar</button><button class="btn gray block" id="back" style="margin-top:8px">Kembali</button><div id="msg"></div></div>';el('save').onclick=function(){var nis=el('nis').value.trim(),name=el('name').value.trim(),p=el('pw').value,cp=el('cpw').value;if(!nis||!name||p.length<6)return setMsg('msg','Lengkapi data. Password minimal 6 karakter.');if(p!==cp)return setMsg('msg','Konfirmasi password tidak sama.');setMsg('msg','Menyimpan pendaftaran…','info');registerStudentFn({classId:state.classId,nis:nis,name:name,password:p}).then(function(){setMsg('msg','Pendaftaran berhasil. Tunggu admin menyetujui akun sebelum login.','success');}).catch(function(e){setMsg('msg',cloudErr(e));});};el('back').onclick=studentChoice;}
function loginStudent(){app.innerHTML='<div class="login card"><h1>Login Siswa</h1><span class="pill">Kelas '+esc(state.classId)+'</span><div class="divider"></div><label>NIS</label><input id="nis" class="input"><label>Password</label><input id="pw" class="input" type="password"><button class="btn block" id="go">Masuk</button><button class="btn gray block" id="back" style="margin-top:8px">Kembali</button><div id="msg"></div></div>';el('go').onclick=function(){var nis=el('nis').value.trim(),p=el('pw').value;if(!nis||!p)return setMsg('msg','NIS dan password wajib.');setMsg('msg','Memeriksa akun…','info');studentLoginFn({classId:state.classId,nis:nis,password:p}).then(function(r){state.student=r.data.student;saveActivity();studentDashboard();}).catch(function(e){setMsg('msg',cloudErr(e));});};el('back').onclick=studentChoice;}
function studentDashboard(){saveActivity();db.collection('examPublic').where('active','==',true).get().then(function(s){var exams=s.docs.map(function(d){return Object.assign({id:d.id},d.data());}).filter(function(x){return !x.allowedClasses||!x.allowedClasses.length||x.allowedClasses.indexOf(state.classId)>=0;});state.exams=exams;app.innerHTML='<div class="top"><div class="brand"><span class="logo">P</span><b>PakKom Exambro</b></div><button class="btn gray small" id="logout">Keluar</button></div><div class="wrap"><div class="card"><span class="pill">Kelas '+esc(state.classId)+'</span><h1>'+esc(state.student.name)+'</h1><p class="muted">NIS: '+esc(state.student.nis)+'</p></div><div class="card"><h2>Ujian Tersedia</h2>'+(!exams.length?'<div class="empty">Belum ada ujian aktif.</div>':exams.map(examCard).join(''))+'</div></div>';el('logout').onclick=function(){logoutStudent('Anda sudah keluar.');};Array.prototype.forEach.call(document.querySelectorAll('.exam-open'),function(b){b.onclick=function(){examPin(b.dataset.id);};});}).catch(function(e){renderHome('Daftar ujian gagal dimuat: '+e.message);});}
function examCard(x){var now=Date.now(),st=x.startAt&&x.startAt.toDate?x.startAt.toDate().getTime():0,en=x.endAt&&x.endAt.toDate?x.endAt.toDate().getTime():0,future=st&&now<st,past=en&&now>en;return '<div class="exam"><div class="row"><div><h3>'+esc(x.name)+'</h3><p class="muted">'+esc(x.subject||'Ujian online')+'</p></div><span class="pill '+(future?'orange':past?'red':'green')+'">'+(future?'Belum mulai':past?'Berakhir':'Aktif')+'</span></div>'+(st?'<p class="smalltext">Mulai: '+esc(fmt(x.startAt))+'</p>':'')+(en?'<p class="smalltext">Selesai: '+esc(fmt(x.endAt))+'</p>':'')+'<button class="btn exam-open" data-id="'+esc(x.id)+'" '+(future||past?'disabled':'')+'>'+(future||past?'Tidak tersedia':'Mulai Ujian')+'</button></div>';}
function examPin(id){var x=state.exams.find(function(a){return a.id===id;});state.currentExam=x;app.innerHTML='<div class="login card"><h1>PIN Ujian</h1><h2>'+esc(x.name)+'</h2><input id="pin" class="input" inputmode="numeric" placeholder="PIN"><button class="btn block" id="open">Buka Ujian</button><button class="btn gray block" id="back" style="margin-top:8px">Kembali</button><div id="msg"></div></div>';el('open').onclick=function(){var p=el('pin').value.trim();if(!p)return setMsg('msg','PIN wajib diisi.');setMsg('msg','Memeriksa PIN…','info');verifyExamPinFn({examId:id,pin:p}).then(function(r){showExam(r.data);}).catch(function(e){setMsg('msg',cloudErr(e));});};el('back').onclick=studentDashboard;}
function showExam(data){var u=data.url;app.innerHTML='<div class="top"><div class="brand"><span class="logo">P</span><b>'+esc(data.name||'Ujian')+'</b></div><button class="btn gray small" id="dash">Dashboard</button></div><div class="wrap"><div class="card"><div class="statusbar"><div><b>'+esc(state.student.name)+'</b> • '+esc(state.classId)+'</div><button class="btn small" id="full">Fullscreen</button></div><div class="divider"></div><iframe class="exam-frame" id="frame" src="'+esc(embedUrl(u))+'" allow="fullscreen"></iframe><p class="muted smalltext">Jika halaman tidak dapat ditampilkan di dalam PakKom Exambro, gunakan tombol berikut.</p><button class="btn gray" id="external">Buka Langsung</button></div></div>';el('dash').onclick=studentDashboard;el('full').onclick=function(){document.documentElement.requestFullscreen&&document.documentElement.requestFullscreen();};el('external').onclick=function(){location.href=u;};}
function embedUrl(u){if(/docs\.google\.com\/forms/i.test(u)&&u.indexOf('embedded=true')<0)return u+(u.indexOf('?')>=0?'&':'?')+'embedded=true';return u;}
function logoutStudent(msg){var p=auth.currentUser&&auth.currentUser.isAnonymous?endStudentSessionFn().catch(function(){}):Promise.resolve();p.then(function(){clearActivity();state={classId:'',student:null,exams:[],currentExam:null};return auth.signOut();}).then(function(){renderHome(msg||'');});}

// ADMIN
function adminLogin(){if(auth.currentUser&&auth.currentUser.isAnonymous){auth.signOut().then(adminLogin);return;}app.innerHTML='<div class="login card"><h1>Login Admin</h1><input id="email" class="input" placeholder="Email"><input id="pass" class="input" type="password" placeholder="Password"><button class="btn block" id="go">Masuk</button><button class="btn gray block" id="back" style="margin-top:8px">Kembali</button><div id="msg"></div></div>';el('go').onclick=function(){auth.signInWithEmailAndPassword(el('email').value.trim(),el('pass').value).then(function(c){return db.collection('admins').doc(c.user.uid).get();}).then(function(d){if(!d.exists||d.data().role!=='admin'||d.data().active!==true)throw new Error('Bukan akun admin aktif.');admin();}).catch(function(e){setMsg('msg',e.message);});};el('back').onclick=function(){renderHome('');};}
function admin(){try{localStorage.setItem(ADMIN_KEY,String(Date.now()));}catch(e){}app.innerHTML='<div class="top"><div class="brand"><span class="logo">P</span><b>PakKom Admin V12</b></div><button class="btn gray small" id="logout">Keluar</button></div><div class="wrap"><h1>Dashboard Admin</h1><div class="grid"><div class="card"><h3>Kelas</h3><button class="btn" id="classes">Kelola Kelas</button></div><div class="card"><h3>Siswa</h3><button class="btn" id="students">Kelola Siswa</button></div><div class="card"><h3>Ujian</h3><button class="btn" id="exams">Kelola Ujian</button></div></div></div>';el('logout').onclick=function(){try{localStorage.removeItem(ADMIN_KEY);}catch(e){}auth.signOut().then(function(){renderHome('');});};el('classes').onclick=classesAdmin;el('students').onclick=studentsAdmin;el('exams').onclick=examsAdmin;}
function hashLocal(secret,salt){return crypto.subtle.digest('SHA-256',new TextEncoder().encode(String(salt)+'|'+String(secret))).then(function(buf){return Array.from(new Uint8Array(buf)).map(function(b){return b.toString(16).padStart(2,'0');}).join('');});}
function salt(){var a=new Uint8Array(16);crypto.getRandomValues(a);return Array.from(a).map(function(b){return b.toString(16).padStart(2,'0');}).join('');}
function classesAdmin(){db.collection('classes').get().then(function(s){var rows=s.docs.map(function(d){var x=d.data();return '<tr><td>'+esc(d.id)+'</td><td>'+(x.active===false?'Nonaktif':'Aktif')+'</td><td><button class="btn gray small cedit" data-id="'+esc(d.id)+'">Password</button></td></tr>';}).join('');app.innerHTML='<div class="top"><b>Kelola Kelas</b><button class="btn gray small" id="back">Admin</button></div><div class="wrap"><div class="card"><h2>Tambah/Atur Kelas</h2><input id="cid" class="input" placeholder="7A"><input id="cpw" class="input" type="password" placeholder="Password baru"><button class="btn green" id="save">Simpan</button></div><div class="card"><div class="table-wrap"><table class="table"><tr><th>Kelas</th><th>Status</th><th>Aksi</th></tr>'+rows+'</table></div></div></div>';el('back').onclick=admin;el('save').onclick=function(){saveClass(el('cid').value.trim().toUpperCase(),el('cpw').value);};Array.prototype.forEach.call(document.querySelectorAll('.cedit'),function(b){b.onclick=function(){var p=prompt('Password baru:');if(p)saveClass(b.dataset.id,p);};});});}
function saveClass(id,p){if(!id||p.length<6)return alert('Kelas dan password minimal 6 karakter.');var s=salt();hashLocal(p,s).then(function(h){return db.collection('classes').doc(id).set({name:id,active:true,passwordHash:h,passwordSalt:s,password:firebase.firestore.FieldValue.delete(),demoPassword:firebase.firestore.FieldValue.delete()},{merge:true});}).then(classesAdmin);}
function studentsAdmin(){db.collection('students').get().then(function(s){adminStudents=s.docs.map(function(d){return Object.assign({id:d.id},d.data());});renderStudentsAdmin();});}
function renderStudentsAdmin(){var rows=adminStudents.map(function(x){return '<tr><td>'+esc(x.nis)+'</td><td>'+esc(x.name)+'</td><td>'+esc(x.classId)+'</td><td>'+(x.approved===false?'<span class="pill orange">Menunggu</span>':'<span class="pill green">Disetujui</span>')+'</td><td>'+(x.approved===false?'<button class="btn green small approve" data-id="'+esc(x.id)+'">Approve</button>':'')+'</td></tr>';}).join('');app.innerHTML='<div class="top"><b>Kelola Siswa</b><button class="btn gray small" id="back">Admin</button></div><div class="wrap"><div class="card"><h2>Upload Excel</h2><p class="muted">Kolom: NIS, Nama, Kelas, Password. Password kosong = 123456.</p><input id="file" type="file" accept=".xlsx,.xls,.csv" class="input"><button class="btn green" id="import">Import</button><div id="imsg"></div></div><div class="card"><div class="table-wrap"><table class="table"><tr><th>NIS</th><th>Nama</th><th>Kelas</th><th>Approval</th><th>Aksi</th></tr>'+rows+'</table></div></div></div>';el('back').onclick=admin;el('import').onclick=importExcel;Array.prototype.forEach.call(document.querySelectorAll('.approve'),function(b){b.onclick=function(){db.collection('students').doc(b.dataset.id).update({approved:true,approvedAt:firebase.firestore.FieldValue.serverTimestamp()}).then(studentsAdmin);};});}
function importExcel(){var f=el('file').files[0];if(!f)return setMsg('imsg','Pilih file Excel terlebih dahulu.');var r=new FileReader();r.onload=function(e){try{var wb=XLSX.read(e.target.result,{type:'array'}),ws=wb.Sheets[wb.SheetNames[0]],rows=XLSX.utils.sheet_to_json(ws,{defval:'',raw:false});processImport(rows);}catch(err){setMsg('imsg',err.message);}};r.readAsArrayBuffer(f);}
function pick(r,names){var keys=Object.keys(r);for(var i=0;i<keys.length;i++){var k=keys[i].toLowerCase().replace(/[^a-z0-9]/g,'');if(names.indexOf(k)>=0)return r[keys[i]];}return '';}
function processImport(rows){var existing={};adminStudents.forEach(function(x){existing[String(x.nis)]=true;});var jobs=[],dup=0,bad=0;rows.forEach(function(r){var nis=String(pick(r,['nis','nomorinduksiswa','nomorinduk'])||'').trim(),name=String(pick(r,['nama','namasiswa','namalengkap'])||'').trim(),cls=String(pick(r,['kelas','class','classid'])||'').trim().toUpperCase(),pw=String(pick(r,['password','pass','katasandi'])||'').trim()||'123456';if(!nis||!name||!cls||pw.length<6){bad++;return;}if(existing[nis]){dup++;return;}existing[nis]=true;jobs.push({nis:nis,name:name,classId:cls,password:pw});});if(!jobs.length)return setMsg('imsg','Tidak ada data baru. Duplikat '+dup+', tidak valid '+bad+'.');Promise.all(jobs.map(function(x){var s=salt();return hashLocal(x.password,s).then(function(h){return db.collection('students').add({nis:x.nis,name:x.name,classId:x.classId,passwordHash:h,passwordSalt:s,active:true,approved:true,registrationSource:'admin-import',createdAt:firebase.firestore.FieldValue.serverTimestamp()});});})).then(function(){setMsg('imsg','Selesai: '+jobs.length+' siswa ditambahkan. Duplikat '+dup+', tidak valid '+bad+'.','success');setTimeout(studentsAdmin,500);}).catch(function(e){setMsg('imsg','Import gagal: '+e.message);});}
function examsAdmin(){Promise.all([db.collection('examPublic').get(),db.collection('examSecrets').get()]).then(function(rs){var sec={};rs[1].docs.forEach(function(d){sec[d.id]=d.data();});var cards=rs[0].docs.map(function(d){var x=d.data();return '<div class="exam"><h3>'+esc(x.name)+'</h3><p class="muted">'+esc(x.subject||'')+'</p><p class="smalltext">Kelas: '+esc((x.allowedClasses||[]).join(', ')||'Semua')+'</p><button class="btn red small del" data-id="'+esc(d.id)+'">Hapus</button></div>';}).join('');app.innerHTML='<div class="top"><b>Kelola Ujian</b><button class="btn gray small" id="back">Admin</button></div><div class="wrap"><div class="card"><h2>Tambah Ujian</h2><input id="ename" class="input" placeholder="Nama ujian"><input id="subject" class="input" placeholder="Mata pelajaran"><input id="url" class="input" placeholder="https://..."><input id="classes" class="input" placeholder="7A,7B atau kosong semua"><input id="pin" class="input" placeholder="PIN"><div class="grid"><input id="start" class="input" type="datetime-local"><input id="end" class="input" type="datetime-local"></div><button class="btn green" id="save">Simpan</button></div><div class="card">'+(cards||'<div class="empty">Belum ada ujian.</div>')+'</div></div>';el('back').onclick=admin;el('save').onclick=saveExam;Array.prototype.forEach.call(document.querySelectorAll('.del'),function(b){b.onclick=function(){if(confirm('Hapus ujian?'))Promise.all([db.collection('examPublic').doc(b.dataset.id).delete(),db.collection('examSecrets').doc(b.dataset.id).delete()]).then(examsAdmin);};});});}
function saveExam(){var name=el('ename').value.trim(),subject=el('subject').value.trim(),url=el('url').value.trim(),pin=el('pin').value.trim(),classes=el('classes').value.split(',').map(function(x){return x.trim().toUpperCase();}).filter(Boolean),st=el('start').value,en=el('end').value;if(!name||!https(url)||!pin)return alert('Nama, URL HTTPS, dan PIN wajib.');var ps=salt();hashLocal(pin,ps).then(function(ph){var data={name:name,subject:subject,allowedClasses:classes,active:true,createdAt:firebase.firestore.FieldValue.serverTimestamp()};if(st)data.startAt=new Date(st);if(en)data.endAt=new Date(en);return db.collection('examPublic').add(data).then(function(ref){return db.collection('examSecrets').doc(ref.id).set({url:url,pinHash:ph,pinSalt:ps});});}).then(examsAdmin).catch(function(e){alert(e.message);});}
home('');
})();
