
(function(){
'use strict';
var app=document.getElementById('builderApp');
if(typeof firebase==='undefined'||typeof firebaseConfig==='undefined'){app.innerHTML='<div class="v20-loading">Konfigurasi Firebase tidak ditemukan.</div>';return}
if(!firebase.apps.length)firebase.initializeApp(firebaseConfig);
var auth=firebase.auth(),db=firebase.firestore(),classes=[],step='info',timer=null;
var draft={title:'',subject:'',classes:[],startAt:'',endAt:'',pin:'',shuffleQuestions:false,shuffleOptions:false,allowBack:true,showScore:false,questions:[]};
function esc(s){return String(s==null?'':s).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]})}
function toast(s){var x=document.createElement('div');x.className='b20-toast';x.textContent=s;document.body.appendChild(x);setTimeout(function(){x.remove()},1800)}
function nq(type){return{id:'q_'+Date.now()+'_'+Math.random().toString(36).slice(2,6),type:type||'multiple_choice',question:'',imageUrl:'',points:1,required:true,options:['','','',''],correctIndex:0,correctIndexes:[],answer:''}}
function save(){clearTimeout(timer);var s=document.getElementById('saveState');if(s)s.textContent='Menyimpan…';timer=setTimeout(function(){sessionStorage.setItem('pakkom_v20_draft',JSON.stringify(draft));var x=document.getElementById('saveState');if(x)x.textContent='✓ Tersimpan otomatis'},400)}
function points(){return draft.questions.reduce(function(a,q){return a+(Number(q.points)||0)},0)}
async function hash(s){var b=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s));return Array.from(new Uint8Array(b)).map(function(x){return x.toString(16).padStart(2,'0')}).join('')}
auth.onAuthStateChanged(async function(u){if(!u)return denied();var a=await db.collection('admins').doc(u.uid).get();if(!a.exists||a.data().active!==true||a.data().role!=='admin')return denied();classes=(await db.collection('classes').get()).docs.map(function(d){return Object.assign({id:d.id},d.data())}).filter(function(x){return x.active!==false});try{var s=JSON.parse(sessionStorage.getItem('pakkom_v20_draft')||'null');if(s)draft=s}catch(e){}if(!draft.questions.length)draft.questions=[nq()];render()})
function denied(){app.innerHTML='<div class="v20-loading"><div><h2>Akses Admin Diperlukan</h2><p>Login dari dashboard PakKom Exambro terlebih dahulu.</p><button class="b20-btn primary" onclick="location.href=\'index.html\'">Kembali</button></div></div>'}
function head(){return '<header class="b20-top"><div class="b20-topbar"><button class="b20-back" id="back">←</button><div class="b20-title"><b>'+esc(draft.title||'Ujian Baru')+'</b><span class="b20-save" id="saveState">✓ Tersimpan otomatis</span></div><button class="b20-btn outline" id="pv">Preview</button></div><nav class="b20-steps">'+[['info','1. Informasi'],['questions','2. Soal'],['settings','3. Pengaturan'],['preview','4. Preview']].map(function(x){return '<button class="b20-step '+(step===x[0]?'active':'')+'" data-step="'+x[0]+'">'+x[1]+'</button>'}).join('')+'</nav></header>'}
function render(){app.innerHTML=head()+'<div class="b20-shell"><main class="b20-main">'+content()+'</main>'+side()+'</div>';bind()}
function content(){if(step==='info')return info();if(step==='questions')return questions();if(step==='settings')return settings();return preview()}
function info(){return '<section class="b20-card"><h2>Informasi Ujian</h2><p class="summary">Tentukan identitas, peserta, dan jadwal ujian.</p><div class="b20-grid2"><div class="b20-field"><label>Nama Ujian</label><input id="title" class="b20-input" value="'+esc(draft.title)+'" placeholder="Penilaian Harian Matematika"></div><div class="b20-field"><label>Mata Pelajaran</label><input id="subject" class="b20-input" value="'+esc(draft.subject)+'" placeholder="Matematika"></div></div><div class="b20-field"><label>Kelas Peserta</label><div class="b20-chips">'+classes.map(function(c){return '<label class="b20-chip"><input class="cls" type="checkbox" value="'+esc(c.id)+'" '+(draft.classes.indexOf(c.id)>=0?'checked':'')+'><span>'+esc(c.name||c.id)+'</span></label>'}).join('')+'</div></div><div class="b20-grid3"><div class="b20-field"><label>Mulai</label><input id="start" class="b20-input" type="datetime-local" value="'+esc(draft.startAt)+'"></div><div class="b20-field"><label>Selesai</label><input id="end" class="b20-input" type="datetime-local" value="'+esc(draft.endAt)+'"></div><div class="b20-field"><label>PIN (opsional)</label><input id="pin" class="b20-input" value="'+esc(draft.pin)+'"></div></div><div class="b20-row"><span class="grow"></span><button class="b20-btn primary" id="next">Simpan & Lanjut →</button></div></section>'}
function qcard(q,i){var ans='';if(q.type==='multiple_choice'||q.type==='multi_select')ans=q.options.map(function(o,j){var ck=q.type==='multiple_choice'?q.correctIndex===j:q.correctIndexes.indexOf(j)>=0;return '<div class="b20-opt"><input class="correct" type="'+(q.type==='multiple_choice'?'radio':'checkbox')+'" name="c'+q.id+'" value="'+j+'" '+(ck?'checked':'')+'><span>'+String.fromCharCode(65+j)+'</span><input class="b20-input opt" data-i="'+j+'" value="'+esc(o)+'" placeholder="Pilihan"><button class="delopt" data-i="'+j+'">×</button></div>'}).join('')+'<button class="b20-btn outline addopt">+ Pilihan</button>';else if(q.type==='true_false')ans='<div class="b20-field"><label>Jawaban benar</label><select class="b20-select answer"><option value="true" '+(q.answer==='true'?'selected':'')+'>Benar</option><option value="false" '+(q.answer==='false'?'selected':'')+'>Salah</option></select></div>';else if(q.type==='short_answer')ans='<div class="b20-field"><label>Jawaban yang diterima</label><input class="b20-input answer" value="'+esc(q.answer)+'"></div>';else ans='<p class="summary">Uraian dinilai manual.</p>';return '<article class="b20-card b20-q" id="q'+i+'"><div class="b20-qhead"><b class="b20-qnum">Soal '+(i+1)+'</b><span class="grow"></span><select class="b20-select b20-qtype type"><option value="multiple_choice">Pilihan Ganda</option><option value="multi_select">Multi Jawaban</option><option value="true_false">Benar / Salah</option><option value="short_answer">Isian Singkat</option><option value="essay">Uraian</option></select></div><textarea class="b20-textarea text" placeholder="Tuliskan pertanyaan...">'+esc(q.question)+'</textarea><div class="b20-grid2" style="margin-top:8px"><div class="b20-field"><label>Gambar (URL, opsional)</label><input class="b20-input image" value="'+esc(q.imageUrl)+'"></div><div class="b20-field"><label>Bobot</label><input class="b20-input points" type="number" min=".1" step=".1" value="'+q.points+'"></div></div>'+ans+'<div class="b20-qfoot"><label><input class="req" type="checkbox" '+(q.required?'checked':'')+'> Wajib</label><span class="grow"></span><button class="b20-btn outline dup">Duplikat</button><button class="b20-btn outline up">↑</button><button class="b20-btn outline down">↓</button><button class="b20-btn danger del">Hapus</button></div></article>'}
function questions(){return draft.questions.map(qcard).join('')+'<div class="b20-toolbar"><button class="b20-btn outline" id="add">+ Soal</button><button class="b20-btn outline" id="bank">📚 Bank Soal</button><button class="b20-btn primary publish" id="set">Pengaturan →</button></div>'}
function settings(){return '<section class="b20-card"><h2>Pengaturan Ujian</h2><div class="b20-checks"><label><input id="sq" type="checkbox" '+(draft.shuffleQuestions?'checked':'')+'> Acak soal</label><label><input id="so" type="checkbox" '+(draft.shuffleOptions?'checked':'')+'> Acak pilihan</label><label><input id="ab" type="checkbox" '+(draft.allowBack?'checked':'')+'> Boleh kembali</label><label><input id="ss" type="checkbox" '+(draft.showScore?'checked':'')+'> Tampilkan nilai</label></div><hr style="border:0;border-top:1px solid var(--line);margin:18px 0"><p class="summary"><b>Keamanan:</b> kunci jawaban disimpan di koleksi admin-only. Draft soal disimpan lokal agar tidak membebani kuota Firestore setiap ketikan.</p><div class="b20-row"><button class="b20-btn outline" id="bs">← Soal</button><span class="grow"></span><button class="b20-btn primary" id="tp">Preview →</button></div></section>'}
function preview(){return '<section class="b20-card"><h2>'+esc(draft.title||'Preview Ujian')+'</h2><p class="summary">'+esc(draft.subject)+' • '+draft.questions.length+' soal • '+points()+' poin</p></section>'+draft.questions.map(function(q,i){var o=(q.type==='multiple_choice'||q.type==='multi_select')?q.options.map(function(x){return '<div class="b20-preview-opt">○ '+esc(x||'Pilihan')+'</div>'}).join(''):(q.type==='true_false'?'<div class="b20-preview-opt">○ Benar</div><div class="b20-preview-opt">○ Salah</div>':'<div class="b20-preview-opt">Jawaban...</div>');return '<article class="b20-card b20-preview-q"><span class="summary">Soal '+(i+1)+' • '+q.points+' poin</span><h3>'+esc(q.question||'(Belum diisi)')+'</h3>'+o+'</article>'}).join('')+'<div class="b20-toolbar"><button class="b20-btn outline" id="bp">← Edit</button><button class="b20-btn primary publish" id="pub">Terbitkan Ujian</button></div>'}
function side(){if(step!=='questions')return '<aside class="b20-side"></aside>';var bad=draft.questions.filter(function(q){return !q.question}).length;return '<aside class="b20-side"><section class="b20-card"><b>Daftar Soal</b><div class="b20-navgrid">'+draft.questions.map(function(q,i){return '<button class="b20-navnum '+(!q.question?'warn':'')+'" data-nav="'+i+'">'+(i+1)+'</button>'}).join('')+'</div><p class="summary">'+draft.questions.length+' soal<br>'+points()+' poin'+(bad?'<br>⚠ '+bad+' belum lengkap':'<br>✓ Semua terisi')+'</p></section></aside>'}
function readInfo(){draft.title=document.getElementById('title').value.trim();draft.subject=document.getElementById('subject').value.trim();draft.startAt=document.getElementById('start').value;draft.endAt=document.getElementById('end').value;draft.pin=document.getElementById('pin').value.trim();draft.classes=[].slice.call(document.querySelectorAll('.cls:checked')).map(function(x){return x.value});save()}
function bind(){document.getElementById('back').onclick=function(){location.href='index.html'};document.getElementById('pv').onclick=function(){step='preview';render()};document.querySelectorAll('.b20-step').forEach(function(x){x.onclick=function(){step=x.dataset.step;render()}});
 if(step==='info'){['title','subject','start','end','pin'].forEach(function(id){document.getElementById(id).oninput=readInfo});document.querySelectorAll('.cls').forEach(function(x){x.onchange=readInfo});document.getElementById('next').onclick=function(){readInfo();step='questions';render()}}
 if(step==='questions')bindQ();
 if(step==='settings'){['sq','so','ab','ss'].forEach(function(id){document.getElementById(id).onchange=function(){draft.shuffleQuestions=document.getElementById('sq').checked;draft.shuffleOptions=document.getElementById('so').checked;draft.allowBack=document.getElementById('ab').checked;draft.showScore=document.getElementById('ss').checked;save()}});document.getElementById('bs').onclick=function(){step='questions';render()};document.getElementById('tp').onclick=function(){step='preview';render()}}
 if(step==='preview'){document.getElementById('bp').onclick=function(){step='questions';render()};document.getElementById('pub').onclick=publish}
 document.querySelectorAll('[data-nav]').forEach(function(x){x.onclick=function(){document.getElementById('q'+x.dataset.nav).scrollIntoView({behavior:'smooth',block:'center'})}})
}
function bindQ(){document.querySelectorAll('.b20-q').forEach(function(c,i){var q=draft.questions[i],t=c.querySelector('.type');t.value=q.type;t.onchange=function(){q.type=t.value;if((q.type==='multiple_choice'||q.type==='multi_select')&&!q.options.length)q.options=['','','',''];save();render()};c.querySelector('.text').oninput=function(){q.question=this.value;save()};c.querySelector('.image').oninput=function(){q.imageUrl=this.value;save()};c.querySelector('.points').oninput=function(){q.points=Number(this.value)||1;save()};c.querySelector('.req').onchange=function(){q.required=this.checked;save()};c.querySelectorAll('.opt').forEach(function(x){x.oninput=function(){q.options[+x.dataset.i]=x.value;save()}});c.querySelectorAll('.correct').forEach(function(x){x.onchange=function(){if(q.type==='multiple_choice')q.correctIndex=+x.value;else q.correctIndexes=[].slice.call(c.querySelectorAll('.correct:checked')).map(function(y){return +y.value});save()}});var a=c.querySelector('.answer');if(a)a.onchange=function(){q.answer=a.value;save()};var ao=c.querySelector('.addopt');if(ao)ao.onclick=function(){q.options.push('');save();render()};c.querySelectorAll('.delopt').forEach(function(x){x.onclick=function(){if(q.options.length<=2)return toast('Minimal 2 pilihan');q.options.splice(+x.dataset.i,1);q.correctIndex=0;q.correctIndexes=[];save();render()}});c.querySelector('.dup').onclick=function(){var z=JSON.parse(JSON.stringify(q));z.id='q_'+Date.now();draft.questions.splice(i+1,0,z);save();render()};c.querySelector('.up').onclick=function(){if(i){var z=draft.questions[i-1];draft.questions[i-1]=q;draft.questions[i]=z;save();render()}};c.querySelector('.down').onclick=function(){if(i<draft.questions.length-1){var z=draft.questions[i+1];draft.questions[i+1]=q;draft.questions[i]=z;save();render()}};c.querySelector('.del').onclick=function(){if(draft.questions.length===1)return toast('Minimal satu soal');draft.questions.splice(i,1);save();render()}});
 document.getElementById('add').onclick=function(){draft.questions.push(nq());save();render()};document.getElementById('bank').onclick=bank;document.getElementById('set').onclick=function(){step='settings';render()}
}
async function bank(){var docs=(await db.collection('questionBank').get()).docs.map(function(d){return Object.assign({id:d.id},d.data())});app.innerHTML=head()+'<div class="b20-shell"><main class="b20-main"><section class="b20-card"><div class="b20-row"><div><h2>Bank Soal</h2><p class="summary">Pilih soal untuk ujian ini.</p></div><span class="grow"></span><button class="b20-btn outline" id="bk">Kembali</button></div>'+docs.map(function(q,i){return '<label class="b20-bank-item"><input type="checkbox" value="'+i+'"><span><b>'+esc(q.question||'Soal')+'</b><small>'+esc(q.subject||'')+' • '+esc(q.type||'')+'</small></span></label>'}).join('')+'<button class="b20-btn primary" id="ba">Tambahkan</button></section></main></div>';document.getElementById('bk').onclick=render;document.getElementById('ba').onclick=function(){document.querySelectorAll('.b20-bank-item input:checked').forEach(function(x){var b=docs[+x.value],q=nq(b.type);q.question=b.question||'';q.imageUrl=b.imageUrl||'';q.points=Number(b.points)||1;q.options=(b.options||['','','','']).slice();q.correctIndex=Number(b.correctIndex)||0;q.correctIndexes=(b.correctIndexes||[]).slice();q.answer=b.answer||'';q.sourceBankId=b.id;draft.questions.push(q)});save();step='questions';render()}}
async function publish(){if(!draft.title||!draft.subject)return toast('Lengkapi nama dan mata pelajaran');if(!draft.classes.length)return toast('Pilih kelas peserta');if(!draft.startAt||!draft.endAt||new Date(draft.endAt)<=new Date(draft.startAt))return toast('Jadwal belum benar');for(var i=0;i<draft.questions.length;i++){var q=draft.questions[i];if(!q.question)return toast('Soal '+(i+1)+' belum lengkap');if((q.type==='multiple_choice'||q.type==='multi_select')&&q.options.some(function(o){return !o}))return toast('Pilihan soal '+(i+1)+' belum lengkap')}
 try{var er=db.collection('examPublic').doc(),eid=er.id,b=db.batch();b.set(er,{name:draft.title,subject:draft.subject,allowedClasses:draft.classes,startAt:firebase.firestore.Timestamp.fromDate(new Date(draft.startAt)),endAt:firebase.firestore.Timestamp.fromDate(new Date(draft.endAt)),active:true,archived:false,examType:'internal',questionCount:draft.questions.length,totalPoints:points(),shuffleQuestions:draft.shuffleQuestions,shuffleOptions:draft.shuffleOptions,allowBack:draft.allowBack,showScore:draft.showScore,createdAt:firebase.firestore.FieldValue.serverTimestamp(),updatedAt:firebase.firestore.FieldValue.serverTimestamp()});if(draft.pin)b.set(db.collection('examSecrets').doc(eid),{pinHash:await hash(draft.pin),updatedAt:firebase.firestore.FieldValue.serverTimestamp()});draft.questions.forEach(function(q,i){var id=eid+'__'+String(i+1).padStart(3,'0');b.set(db.collection('internalExamQuestions').doc(id),{examId:eid,order:i+1,type:q.type,question:q.question,imageUrl:q.imageUrl||'',points:Number(q.points)||1,required:q.required!==false,options:(q.type==='multiple_choice'||q.type==='multi_select')?q.options:[],sourceBankId:q.sourceBankId||null,snapshotVersion:1});var s={examId:eid,type:q.type};if(q.type==='multiple_choice')s.correctIndex=q.correctIndex;else if(q.type==='multi_select')s.correctIndexes=q.correctIndexes;else if(q.type==='true_false'||q.type==='short_answer')s.answer=q.answer;else s.manualGrading=true;b.set(db.collection('internalQuestionSecrets').doc(id),s)});await b.commit();sessionStorage.removeItem('pakkom_v20_draft');toast('Ujian berhasil diterbitkan');setTimeout(function(){location.href='index.html'},900)}catch(e){toast('Gagal: '+(e.code||e.message))}
}
})();
