'use strict';
window.PAKKOM_MODULES=window.PAKKOM_MODULES||[];window.PAKKOM_MODULES.push('admin-exams');
async function examControlCenter(){
 if(!(await isAdmin()))return adminLogin();stopRealtimeMonitor();await syncServerClock();
 var first=await Promise.all([db.collection('examPublic').get(),db.collection('students').get(),db.collection('examAttempts').get()]);
 window.__pakkomMonitorData={exams:first[0].docs.map(function(d){return Object.assign({id:d.id},d.data());}),students:first[1].docs.map(function(d){return Object.assign({id:d.id},d.data());}),attempts:first[2].docs.map(function(d){return Object.assign({id:d.id},d.data());})};
 top('Exam Control Center','<div class="wrap"><div class="card control-head"><div class="section-head"><div><h2>Monitoring Ujian Real-time</h2><p class="muted">Status diperbarui otomatis. '+serverClockLabel()+' digunakan untuk menentukan jadwal.</p></div><span class="live-indicator"><i></i> LIVE</span></div><div class="grid result-filter-grid"><select id="monitorExam"></select><select id="monitorClass"><option value="">Semua kelas</option></select></div><div id="monitorSummary"></div></div><div class="card"><div id="monitorTable"></div></div></div>',function(){stopRealtimeMonitor();admin();},'Admin');
 populateMonitorFilters();renderMonitor();
 monitorUnsubs.push(db.collection('examPublic').onSnapshot(function(q){window.__pakkomMonitorData.exams=q.docs.map(function(d){return Object.assign({id:d.id},d.data());});populateMonitorFilters(true);renderMonitor();}));
 monitorUnsubs.push(db.collection('students').onSnapshot(function(q){window.__pakkomMonitorData.students=q.docs.map(function(d){return Object.assign({id:d.id},d.data());});populateMonitorFilters(true);renderMonitor();}));
 monitorUnsubs.push(db.collection('examAttempts').onSnapshot(function(q){window.__pakkomMonitorData.attempts=q.docs.map(function(d){return Object.assign({id:d.id},d.data());});renderMonitor();}));
}
function populateMonitorFilters(preserve){
 var d=window.__pakkomMonitorData||{exams:[],students:[]},exSel=el('monitorExam'),clSel=el('monitorClass');if(!exSel||!clSel)return;
 var oldE=preserve?exSel.value:'',oldC=preserve?clSel.value:'';
 var exs=sortExamsBySchedule(d.exams).slice().reverse(),classes=[...new Set(d.students.map(function(x){return x.classId;}).filter(Boolean))].sort(function(a,b){return String(a).localeCompare(String(b),undefined,{numeric:true});});
 exSel.innerHTML='<option value="">Pilih ujian</option>'+exs.map(function(x){return '<option value="'+esc(x.id)+'">'+esc(x.name)+' — '+esc(dateInfo(x.startAt).short)+' '+esc(timeOnly(x.startAt))+'</option>';}).join('');
 clSel.innerHTML='<option value="">Semua kelas</option>'+classes.map(function(c){return '<option value="'+esc(c)+'">'+esc(c)+'</option>';}).join('');
 if(oldE&&d.exams.some(function(x){return x.id===oldE;}))exSel.value=oldE;else if(exs.length)exSel.value=exs[0].id;if(oldC)clSel.value=oldC;
 exSel.onchange=renderMonitor;clSel.onchange=renderMonitor;
}
function monitorRows(){
 var d=window.__pakkomMonitorData||{exams:[],students:[],attempts:[]},eid=el('monitorExam')?el('monitorExam').value:'',cls=el('monitorClass')?el('monitorClass').value:'';if(!eid)return [];
 var ex=d.exams.find(function(x){return String(x.id)===String(eid);});if(!ex)return [];
 var amap={};d.attempts.forEach(function(a){amap[String(a.studentId)+'__'+String(a.examId)]=a;});
 return d.students.filter(function(st){return st.approved===true&&st.active===true&&(!cls||String(st.classId)===cls)&&(!Array.isArray(ex.allowedClasses)||!ex.allowedClasses.length||ex.allowedClasses.indexOf(st.classId)>=0);}).map(function(st){var at=amap[String(st.id)+'__'+String(ex.id)]||null,ended=toDate(ex.endAt)&&nowMs()>toDate(ex.endAt).getTime(),status=at&&at.status==='completed'?'completed':at&&at.status==='in_progress'?'in_progress':ended?'missed':'not_started';return {student:st,exam:ex,attempt:at,status:status};}).sort(function(a,b){return String(a.student.classId||'').localeCompare(String(b.student.classId||''),undefined,{numeric:true})||String(a.student.name||'').localeCompare(String(b.student.name||''));});
}
function violationLogHtml(at){var logs=at&&Array.isArray(at.violationLog)?at.violationLog:[];if(!logs.length)return '<span class="muted">—</span>';return '<details class="violation-log"><summary>'+logs.length+' catatan</summary>'+logs.map(function(v){var dt=v.at?new Date(v.at):null;return '<div><b>Peringatan '+esc(v.count||'')+'</b><span>'+(dt&&!isNaN(dt)?esc(dt.toLocaleTimeString('id-ID',{hour:'2-digit',minute:'2-digit',second:'2-digit'}).replace(/\\./g,':')):'-')+' • '+esc(v.label||v.type||'Pelanggaran')+'</span></div>';}).join('')+'</details>';}
function renderMonitor(){
 var rows=monitorRows();if(!el('monitorTable'))return;
 var counts={not_started:0,missed:0,in_progress:0,completed:0,violations:0};rows.forEach(function(r){counts[r.status]++;if(r.attempt&&(r.attempt.violationCount>0||r.attempt.completionReason==='left_exam_twice'))counts.violations++;});
 el('monitorSummary').innerHTML='<div class="result-stats result-stats-polish"><div class="stat-chip stat-wait"><b>'+counts.not_started+'</b><span>Belum Ujian</span></div><div class="stat-chip stat-live"><b>'+counts.in_progress+'</b><span>Sedang Mengerjakan</span></div><div class="stat-chip stat-done"><b>'+counts.completed+'</b><span>Selesai</span></div><div class="stat-chip stat-missed"><b>'+counts.missed+'</b><span>Tidak Ujian</span></div><div class="stat-chip stat-violation"><b>'+counts.violations+'</b><span>Ada Pelanggaran</span></div><div class="stat-chip stat-total"><b>'+rows.length+'</b><span>Peserta</span></div></div>';
 function sh(r){if(r.status==='in_progress')return '<span class="pill green">Sedang Mengerjakan</span>';if(r.status==='completed'){var v=r.attempt&&(r.attempt.completionReason==='left_exam_twice'||r.attempt.autoCompleted);return '<span class="pill '+(v?'red':'orange')+'">'+(v?'Selesai • Pelanggaran':'Selesai')+'</span>';}if(r.status==='missed')return '<span class="pill gray">Tidak Ujian</span>';return '<span class="pill gray">Belum Ujian</span>';}
 var table='<div class="table-wrap"><table class="table monitor-table"><tr><th>Kelas</th><th>NIS</th><th>Nama</th><th>Status</th><th>Mulai</th><th>Selesai</th><th>Pelanggaran</th><th>Aksi</th></tr>'+rows.map(function(r){var at=r.attempt;return '<tr><td>'+esc(r.student.classId||'-')+'</td><td>'+esc(r.student.nis||'-')+'</td><td><b>'+esc(r.student.name||'-')+'</b></td><td>'+sh(r)+'</td><td>'+esc(formatClock(at&&at.startedAt))+'</td><td>'+esc(formatClock(at&&at.completedAt))+'</td><td>'+violationLogHtml(at)+'</td><td>'+(at?'<button class="btn green small monitor-reset" data-id="'+esc(at.id)+'" data-name="'+esc(r.student.name||r.student.nis)+'">Izinkan Ulang</button>':'<span class="muted">—</span>')+'</td></tr>';}).join('')+'</table></div>';
 el('monitorTable').innerHTML=rows.length?table:'<div class="empty">Pilih ujian atau belum ada peserta.</div>';
 document.querySelectorAll('.monitor-reset').forEach(function(b){b.onclick=function(){resetExamAttempt(b.dataset.id,b.dataset.name,true);};});
}

async function examResultsAdmin(){
 if(!(await isAdmin()))return adminLogin();
 var data=await Promise.all([db.collection('examPublic').get(),db.collection('students').get(),db.collection('examAttempts').get()]);
 var exams=data[0].docs.map(function(d){return Object.assign({id:d.id},d.data());}).sort(function(a,b){return String(a.name||'').localeCompare(String(b.name||''));});
 var students=data[1].docs.map(function(d){return Object.assign({id:d.id},d.data());});
 var attempts=data[2].docs.map(function(d){return Object.assign({id:d.id},d.data());});
 var classes=[...new Set(students.map(function(x){return x.classId;}).filter(Boolean))].sort(function(a,b){return String(a).localeCompare(String(b),undefined,{numeric:true});});
 window.__pakkomResultData={exams:exams,students:students,attempts:attempts};
 top('Hasil Pengerjaan Ujian','<div class="wrap"><div class="card result-filter-card"><div class="section-head"><div><h2>Status Pengerjaan Siswa</h2><p class="muted">Belum Ujian = jadwal belum berakhir dan belum membuka soal. Tidak Ujian = jadwal sudah lewat tanpa aktivitas pengerjaan. Status pelanggaran ditandai khusus.</p></div></div><div class="grid result-filter-grid"><select id="resultExam"><option value="">Semua ujian</option>'+exams.map(function(x){return '<option value="'+esc(x.id)+'">'+esc(x.name)+'</option>';}).join('')+'</select><select id="resultClass"><option value="">Semua kelas</option>'+classes.map(function(c){return '<option value="'+esc(c)+'">'+esc(c)+'</option>';}).join('')+'</select></div><div id="resultSummary"></div></div><div class="card"><div id="resultTable"></div></div></div>',admin,'Admin');
 el('resultExam').onchange=renderExamResults;el('resultClass').onchange=renderExamResults;renderExamResults();
}
function renderExamResults(){
 var d=window.__pakkomResultData||{exams:[],students:[],attempts:[]},eid=el('resultExam')?el('resultExam').value:'',cls=el('resultClass')?el('resultClass').value:'';
 var attemptMap={};
 d.attempts.forEach(function(a){attemptMap[String(a.studentId)+'__'+String(a.examId)]=a;});
 var selectedExams=d.exams.filter(function(e){return !eid||String(e.id)===eid;});
 var selectedStudents=d.students.filter(function(st){return st.approved===true&&st.active===true&&(!cls||String(st.classId)===cls);});
 var rows=[];
 selectedExams.forEach(function(ex){
   selectedStudents.forEach(function(st){
     var allowed=!Array.isArray(ex.allowedClasses)||!ex.allowedClasses.length||ex.allowedClasses.indexOf(st.classId)>=0;
     if(!allowed)return;
     var at=attemptMap[String(st.id)+'__'+String(ex.id)]||null;
     var ended=toDate(ex.endAt)&&nowMs()>toDate(ex.endAt).getTime();rows.push({student:st,exam:ex,attempt:at,status:at&&at.status==='completed'?'completed':at&&at.status==='in_progress'?'in_progress':ended?'missed':'not_started'});
   });
 });
 rows.sort(function(a,b){return String(a.student.classId||'').localeCompare(String(b.student.classId||''),undefined,{numeric:true})||String(a.student.name||a.student.nis||'').localeCompare(String(b.student.name||b.student.nis||''))||String(a.exam.name||'').localeCompare(String(b.exam.name||''));});
 var completed=rows.filter(function(r){return r.status==='completed';}).length;
 var inprogress=rows.filter(function(r){return r.status==='in_progress';}).length;
 var notstarted=rows.filter(function(r){return r.status==='not_started';}).length;
 var missed=rows.filter(function(r){return r.status==='missed';}).length;
 var violations=rows.filter(function(r){return r.status==='completed'&&r.attempt&&(r.attempt.completionReason==='left_exam_twice'||r.attempt.autoCompleted===true);}).length;
 if(el('resultSummary'))el('resultSummary').innerHTML='<div class="result-stats result-stats-polish"><div class="stat-chip stat-wait"><b>'+notstarted+'</b><span>Belum Ujian</span></div><div class="stat-chip stat-missed"><b>'+missed+'</b><span>Tidak Ujian</span></div><div class="stat-chip stat-live"><b>'+inprogress+'</b><span>Sedang Mengerjakan</span></div><div class="stat-chip stat-done"><b>'+completed+'</b><span>Sudah Ujian</span></div><div class="stat-chip stat-violation"><b>'+violations+'</b><span>Pelanggaran</span></div><div class="stat-chip stat-total"><b>'+rows.length+'</b><span>Total Peserta</span></div></div>';
 function statusHTML(r){if(r.status==='completed'){var v=r.attempt&&(r.attempt.completionReason==='left_exam_twice'||r.attempt.autoCompleted===true);return '<span class="pill '+(v?'red':'orange')+'">'+(v?'Sudah Ujian • Pelanggaran':'Sudah Ujian')+'</span>';}if(r.status==='in_progress')return '<span class="pill green">Sedang Mengerjakan</span>';if(r.status==='missed')return '<span class="pill gray">Tidak Ujian</span>';return '<span class="pill gray">Belum Ujian</span>';}
 function noteHTML(r){if(r.status==='completed'&&r.attempt&&(r.attempt.completionReason==='left_exam_twice'||r.attempt.autoCompleted===true))return '<div class="violation-text">Otomatis dikunci: keluar/pindah tab 2×</div>'+violationLogHtml(r.attempt);if(r.status==='missed')return '<span class="muted">Jadwal berakhir tanpa pengerjaan</span>';return '<span class="muted">—</span>'; }
 function actionHTML(r){return r.status==='completed'&&r.attempt?'<button class="btn green small result-reset" data-id="'+esc(r.attempt.id)+'" data-name="'+esc(r.student.name||r.student.nis||'siswa')+'">Aktifkan Ulang</button>':'<span class="muted">—</span>';}
 var table='<div class="result-desktop"><div class="table-wrap"><table class="table"><tr><th>Kelas</th><th>NIS</th><th>Nama</th><th>Ujian</th><th>Status</th><th>Keterangan</th><th>Aksi</th></tr>'+rows.map(function(r){return '<tr><td>'+esc(r.student.classId||'-')+'</td><td>'+esc(r.student.nis||'-')+'</td><td><b>'+esc(r.student.name||'-')+'</b></td><td>'+esc(r.exam.name||'-')+'</td><td>'+statusHTML(r)+'</td><td>'+noteHTML(r)+'</td><td>'+actionHTML(r)+'</td></tr>';}).join('')+'</table></div></div>';
 var cards='<div class="result-mobile">'+rows.map(function(r){return '<article class="result-student-card '+esc(r.status)+'"><div class="result-card-head"><div><b>'+esc(r.student.name||'-')+'</b><span>NIS '+esc(r.student.nis||'-')+' • Kelas '+esc(r.student.classId||'-')+'</span></div>'+statusHTML(r)+'</div><div class="result-card-exam">'+esc(r.exam.name||'-')+'</div><div class="result-card-note">'+noteHTML(r)+'</div><div class="result-card-action">'+actionHTML(r)+'</div></article>';}).join('')+'</div>';
 var html=rows.length?table+cards:'<div class="empty">Tidak ada peserta untuk ujian/kelas yang dipilih.</div>';
 if(el('resultTable'))el('resultTable').innerHTML=html;
 document.querySelectorAll('.result-reset').forEach(function(b){b.onclick=function(){resetExamAttempt(b.dataset.id,b.dataset.name);};});
}
async function resetExamAttempt(id,name,fromMonitor){
 var ok=await pakkomConfirm('Aktifkan kembali akses ujian untuk '+name+'? Status Sudah Ujian akan dihapus sehingga siswa dapat memulai ujian lagi.','PakKom Exambro');if(!ok)return;
 try{await db.collection('examAttempts').doc(id).delete();await pakkomAlert('Akses ujian siswa sudah diaktifkan kembali.');if(fromMonitor)renderMonitor();else examResultsAdmin();}catch(e){pakkomAlert('Gagal mengaktifkan kembali: '+(e.code||e.message));}
}

function examAdminStatus(x){var n=nowMs(),st=toDate(x.startAt),en=toDate(x.endAt);if(x.archived===true)return {label:'Diarsipkan',cls:'gray'};if(x.active===false)return {label:'Draft/Nonaktif',cls:'gray'};if(st&&n<st.getTime())return {label:'Akan Datang',cls:'orange'};if(en&&n>en.getTime())return {label:'Selesai',cls:'gray'};return {label:'Berlangsung',cls:'green'};}
async function examsAdmin(){
 if(!(await isAdmin()))return adminLogin();
 var pair=await Promise.all([db.collection('examPublic').get(),db.collection('students').get()]);
 var list=sortExamsBySchedule(pair[0].docs.map(function(d){return Object.assign({id:d.id},d.data());}));
 var students=pair[1].docs.map(function(d){return Object.assign({id:d.id},d.data());});
 var palette=['blue','green','purple','orange'];
 var cards=list.map(function(x,i){
  var st=toDate(x.startAt),status=examAdminStatus(x),day=st?String(st.getDate()).padStart(2,'0'):'--',mon=st?st.toLocaleDateString('id-ID',{month:'short'}).replace('.','').toUpperCase():'';
  var allowed=x.allowedClasses||[],participants=students.filter(function(s){
  if(s.approved!==true||s.active!==true)return false;
  return !allowed.length||allowed.indexOf(String(s.classId||'').toUpperCase())>=0;
 }).length;
  var classes=allowed.join(', ')||'Semua kelas';
  return '<article class="exam-schedule-card"><div class="schedule-date '+palette[i%4]+'"><b>'+esc(day)+'</b><small>'+esc(mon)+'</small></div><div class="schedule-main"><div class="schedule-title-row"><div><h3>'+esc(x.name||'Ujian')+'</h3><p>'+esc(x.subject||'Ujian online')+'</p></div><button class="kebab exam-kebab" aria-label="Aksi ujian" data-id="'+esc(x.id)+'" data-active="'+(x.active===false?'0':'1')+'" data-archived="'+(x.archived===true?'1':'0')+'">⋮</button></div><div class="schedule-lines"><span>'+uiIcon('calendar')+esc(st?st.toLocaleDateString('id-ID',{weekday:'long',day:'numeric',month:'long',year:'numeric'}):'Tanggal belum diatur')+'</span><span>'+uiIcon('clock')+esc(timeOnly(x.startAt))+' - '+esc(timeOnly(x.endAt))+'</span><span>'+uiIcon('people')+participants+' peserta</span></div><div class="schedule-foot"><span class="pill '+status.cls+'">'+status.label+'</span><span class="class-list">'+esc(classes)+'</span></div></div></article>';
 }).join('');
 if(!cards)cards='<div class="empty">Belum ada ujian. Tekan <b>Tambah Ujian</b> untuk membuat jadwal pertama.</div>';
 var today=new Date(),dateVal=today.getFullYear()+'-'+String(today.getMonth()+1).padStart(2,'0')+'-'+String(today.getDate()).padStart(2,'0');
 var addForm='<section id="addExamPanel" class="card exam-create-panel hidden-panel"><div class="section-head"><div><h2>Tambah Ujian</h2><p class="muted">Lengkapi informasi, peserta, keamanan, dan jadwal.</p></div><button class="sheet-close" id="closeExamForm">×</button></div><div class="form-section"><div class="form-section-title"><span class="form-num">1</span>Informasi Ujian</div><div class="form-grid-2"><div class="field"><label>Nama Ujian</label><input id="ename" class="input" placeholder="Contoh: Penilaian Harian 1"></div><div class="field"><label>Mata Pelajaran</label><input id="esub" class="input" placeholder="Contoh: Matematika"></div></div><div class="field"><label>Link Ujian</label><input id="eurl" class="input" placeholder="https://forms.google.com/... atau link Wayground"><div class="field-help">Gunakan link HTTPS. Link join Wayground dapat langsung digunakan tanpa menampilkan kode join terpisah.</div></div></div><div class="form-section"><div class="form-section-title"><span class="form-num">2</span>Peserta & Keamanan</div><div class="form-grid-2"><div class="field"><label>Kelas Peserta</label><input id="eclass" class="input" placeholder="7A,7B,7C atau kosong untuk semua kelas"></div><div class="field"><label>PIN Ujian</label><input id="epin" class="input" type="password" inputmode="numeric" placeholder="Masukkan PIN ujian"></div></div></div><div class="form-section"><div class="form-section-title"><span class="form-num">3</span>Jadwal</div><div class="form-grid-3"><div class="field"><label>Tanggal</label><input id="edate" class="input" type="date" value="'+dateVal+'"></div><div class="field"><label>Jam Mulai</label><input id="estime" class="input" type="time" value="08:00"></div><div class="field"><label>Jam Selesai</label><input id="eetime" class="input" type="time" value="10:00"></div></div><div id="schedulePreview" class="schedule-preview"></div></div><button class="btn green block" id="saveExam">Simpan & Jadwalkan Ujian</button><div id="examSaveMsg"></div></section>';
 var body='<main class="wrap exam-admin-v166"><div class="page-title-row"><div><h1>Kelola Ujian</h1><p class="muted">Daftar jadwal ujian.</p></div><div class="page-actions"><button class="btn gray" id="downloadExamTemplate">Template</button><label class="btn outline file-btn">⇧ Import Excel<input id="examImportFile" type="file" accept=".xlsx,.xls,.csv" hidden></label><button class="btn outline add-exam-button" id="toggleExamForm">＋ Tambah Ujian</button></div></div>'+addForm+'<section class="exam-schedule-list">'+cards+'</section></main>';
 top('Kelola Ujian',body,admin,'Dashboard');

 function updatePreview(){var d=el('edate').value,st=el('estime').value,en=el('eetime').value;if(!d)return el('schedulePreview').innerHTML='Pilih tanggal ujian.';var dt=new Date(d+'T'+(st||'00:00'));el('schedulePreview').innerHTML='<b>'+esc(dt.toLocaleDateString('id-ID',{weekday:'long',day:'numeric',month:'long',year:'numeric'}))+'</b> • '+esc(st||'--:--')+' sampai '+esc(en||'--:--');}
 ['edate','estime','eetime'].forEach(function(id){el(id).oninput=updatePreview;});updatePreview();
 el('saveExam').onclick=saveExam;el('downloadExamTemplate').onclick=downloadExamTemplate;el('examImportFile').onchange=importExamFile;
 el('toggleExamForm').onclick=function(){el('addExamPanel').classList.toggle('hidden-panel');if(!el('addExamPanel').classList.contains('hidden-panel'))el('addExamPanel').scrollIntoView({behavior:'smooth',block:'start'});};
 el('closeExamForm').onclick=function(){el('addExamPanel').classList.add('hidden-panel');};
 document.querySelectorAll('.exam-kebab').forEach(function(b){b.onclick=function(){openExamActionSheet(b.dataset.id,b.dataset.active==='1',b.dataset.archived==='1');};});
}
function openExamActionSheet(id,isActive,isArchived){
 var d=document.createElement('div');d.className='mobile-sheet-backdrop';d.innerHTML='<div class="mobile-sheet exam-action-sheet"><div class="sheet-handle"></div><div class="sheet-title-row"><div><h2>Aksi Ujian</h2><p class="muted">Pilih tindakan untuk jadwal ini.</p></div><button class="sheet-close">×</button></div><button data-act="edit">✎ <span><b>Edit</b><small>Ubah detail, waktu, link, PIN</small></span></button><button data-act="duplicate">▣ <span><b>Duplikat</b><small>Buat salinan ujian</small></span></button><button data-act="toggle">'+(isActive?'Ⅱ':'▶')+' <span><b>'+(isActive?'Nonaktifkan':'Aktifkan')+'</b><small>Atur akses siswa</small></span></button><button data-act="archive">□ <span><b>'+(isArchived?'Buka Arsip':'Arsipkan')+'</b><small>'+(isArchived?'Kembalikan dari arsip':'Sembunyikan tanpa menghapus data')+'</small></span></button><button class="danger" data-act="delete">♲ <span><b>Hapus</b><small>Hapus ujian dan status pengerjaan</small></span></button></div>';
 document.body.appendChild(d);function close(){d.remove();}d.onclick=function(e){if(e.target===d)close();};d.querySelector('.sheet-close').onclick=close;
 d.querySelectorAll('[data-act]').forEach(function(b){b.onclick=function(){var a=b.dataset.act;close();if(a==='edit')editExam(id);else if(a==='duplicate')duplicateExam(id);else if(a==='toggle')toggleExam(id,isActive);else if(a==='archive')archiveExam(id,isArchived);else if(a==='delete')deleteExam(id);};});
}
async function saveExam(){
 var name=el('ename').value.trim(),sub=el('esub').value.trim(),url=el('eurl').value.trim(),pin=el('epin').value.trim(),classes=el('eclass').value.split(',').map(function(x){return x.trim().toUpperCase();}).filter(Boolean),date=el('edate').value,stime=el('estime').value,etime=el('eetime').value;
 if(!name||!sub||!https(url)||!pin||!date||!stime||!etime){msg('examSaveMsg','Nama ujian, mata pelajaran, link HTTPS, PIN, tanggal, jam mulai, dan jam selesai wajib diisi.');return;}
 var start=new Date(date+'T'+stime),end=new Date(date+'T'+etime);if(end<=start){msg('examSaveMsg','Jam selesai harus setelah jam mulai.');return;}
 try{var data={name:name,subject:sub,url:url,allowedClasses:classes,active:true,archived:false,startAt:start,endAt:end,scheduleDate:date,createdAt:firebase.firestore.FieldValue.serverTimestamp()};var ref=await db.collection('examPublic').add(data);await db.collection('examSecrets').doc(ref.id).set({pinHash:await sha256(pin)});await pakkomAlert('Ujian berhasil dijadwalkan untuk '+start.toLocaleDateString('id-ID',{weekday:'long',day:'numeric',month:'long',year:'numeric'})+' pukul '+stime+'.');examsAdmin();}catch(e){msg('examSaveMsg','Ujian gagal disimpan: '+(e.code||e.message));}
}
async function duplicateExam(id){
 if(!(await isAdmin()))return adminLogin();
 try{var pair=await Promise.all([db.collection('examPublic').doc(id).get(),db.collection('examSecrets').doc(id).get()]);if(!pair[0].exists)return pakkomAlert('Ujian tidak ditemukan.');var x=pair[0].data(),copy=Object.assign({},x);delete copy.createdAt;delete copy.updatedAt;copy.name=String(x.name||'Ujian')+' (Salinan)';copy.active=false;copy.archived=false;copy.createdAt=firebase.firestore.FieldValue.serverTimestamp();var ref=await db.collection('examPublic').add(copy);if(pair[1].exists){var sec=pair[1].data();await db.collection('examSecrets').doc(ref.id).set({pinHash:sec.pinHash||'',createdAt:firebase.firestore.FieldValue.serverTimestamp()});}await pakkomAlert('Ujian berhasil diduplikat dalam kondisi Nonaktif. Edit kelas/jadwal terlebih dahulu, lalu aktifkan.');examsAdmin();}catch(e){pakkomAlert('Ujian gagal diduplikat: '+(e.code||e.message));}
}
async function editExam(id){if(!(await isAdmin()))return adminLogin();try{var pair=await Promise.all([db.collection('examPublic').doc(id).get(),db.collection('examSecrets').doc(id).get()]);if(!pair[0].exists)return pakkomAlert('Ujian tidak ditemukan.');var x=pair[0].data(),sd=toDate(x.startAt),ed=toDate(x.endAt),date=sd?(sd.getFullYear()+'-'+String(sd.getMonth()+1).padStart(2,'0')+'-'+String(sd.getDate()).padStart(2,'0')):'',st=sd?(String(sd.getHours()).padStart(2,'0')+':'+String(sd.getMinutes()).padStart(2,'0')):'',en=ed?(String(ed.getHours()).padStart(2,'0')+':'+String(ed.getMinutes()).padStart(2,'0')):'';top('Edit Ujian','<div class="wrap"><div class="card"><h2>'+esc(x.name||'Edit Ujian')+'</h2><div class="form-grid-2"><div class="field"><label>Nama Ujian</label><input id="xname" class="input" value="'+esc(x.name||'')+'"></div><div class="field"><label>Mata Pelajaran</label><input id="xsub" class="input" value="'+esc(x.subject||'')+'"></div></div><label>Link Ujian</label><input id="xurl" class="input" value="'+esc(x.url||'')+'"><label>Kelas Peserta</label><input id="xclass" class="input" value="'+esc((x.allowedClasses||[]).join(','))+'"><div class="form-grid-3"><div class="field"><label>Tanggal</label><input id="xdate" class="input" type="date" value="'+esc(date)+'"></div><div class="field"><label>Jam Mulai</label><input id="xstart" class="input" type="time" value="'+esc(st)+'"></div><div class="field"><label>Jam Selesai</label><input id="xend" class="input" type="time" value="'+esc(en)+'"></div></div><label>PIN Baru <span class="muted">(kosongkan jika tidak diganti)</span></label><input id="xpin" class="input" type="password" inputmode="numeric" placeholder="PIN lama tidak ditampilkan"><div class="actions"><button class="btn green" id="saveEditExam">Simpan Perubahan</button><button class="btn gray" id="cancelEditExam">Batal</button></div><div id="editExamMsg"></div></div></div>',examsAdmin,'Kelola Ujian');el('saveEditExam').onclick=function(){saveExamEdit(id);};el('cancelEditExam').onclick=examsAdmin;}catch(e){pakkomAlert('Ujian tidak dapat dibuka: '+(e.code||e.message));}}
async function saveExamEdit(id){var name=el('xname').value.trim(),sub=el('xsub').value.trim(),url=el('xurl').value.trim(),classes=el('xclass').value.split(',').map(function(v){return v.trim().toUpperCase();}).filter(Boolean),date=el('xdate').value,st=el('xstart').value,en=el('xend').value,pin=el('xpin').value.trim();if(!name||!sub||!https(url)||!date||!st||!en)return msg('editExamMsg','Lengkapi nama, pelajaran, link HTTPS, tanggal, dan waktu.');var start=new Date(date+'T'+st),end=new Date(date+'T'+en);if(end<=start)return msg('editExamMsg','Jam selesai harus setelah jam mulai.');try{await db.collection('examPublic').doc(id).update({name:name,subject:sub,url:url,allowedClasses:classes,startAt:start,endAt:end,scheduleDate:date,updatedAt:firebase.firestore.FieldValue.serverTimestamp()});if(pin)await db.collection('examSecrets').doc(id).set({pinHash:await sha256(pin),updatedAt:firebase.firestore.FieldValue.serverTimestamp()},{merge:true});await pakkomAlert('Detail ujian berhasil diperbarui.');examsAdmin();}catch(e){msg('editExamMsg','Perubahan gagal disimpan: '+(e.code||e.message));}}
async function toggleExam(id,a){await db.collection('examPublic').doc(id).update({active:!a,archived:false});examsAdmin();}
async function archiveExam(id,isArchived){var ok=await pakkomConfirm((isArchived?'Keluarkan ujian ini dari arsip?':'Arsipkan ujian ini? Ujian tidak akan tampil di portal siswa, tetapi data pengerjaan tetap disimpan.'));if(!ok)return;await db.collection('examPublic').doc(id).update({archived:!isArchived,active:isArchived?true:false,updatedAt:firebase.firestore.FieldValue.serverTimestamp()});examsAdmin();}
async function deleteExam(id){var ok=await pakkomConfirm('Hapus ujian ini? Detail ujian, PIN, dan seluruh status pengerjaan ujian ini akan dihapus.');if(!ok)return;try{await db.collection('examPublic').doc(id).delete();await db.collection('examSecrets').doc(id).delete().catch(function(){});var q=await db.collection('examAttempts').where('examId','==',id).get();for(var i=0;i<q.docs.length;i+=400){var batch=db.batch();q.docs.slice(i,i+400).forEach(function(d){batch.delete(d.ref);});await batch.commit();}var sq=await db.collection('examScores').where('examId','==',id).get();for(var j=0;j<sq.docs.length;j+=400){var sb=db.batch();sq.docs.slice(j,j+400).forEach(function(d){sb.delete(d.ref);});await sb.commit();}examsAdmin();}catch(e){pakkomAlert('Ujian gagal dihapus: '+(e.code||e.message));}}

function showNetworkState(offline){
 var old=el('networkBanner');if(old)old.remove();if(!state.currentExam)return;
 var b=document.createElement('div');b.id='networkBanner';b.className='network-banner '+(offline?'offline':'online');b.innerHTML=offline?'<b>Koneksi internet terputus.</b> Ujian tidak dihitung sebagai pelanggaran. Jangan menutup halaman; sistem akan menyambung kembali.':'<b>Koneksi kembali.</b> Attempt ujian yang sama tetap aktif.';document.body.appendChild(b);if(!offline)setTimeout(function(){if(b.parentNode)b.remove();},3500);
}
