'use strict';
window.PAKKOM_MODULES=window.PAKKOM_MODULES||[];window.PAKKOM_MODULES.push('builder-ui');
function head(){return '<header class="b20-top"><div class="b20-topbar"><button class="b20-back" id="back">←</button><div class="b20-title"><b>'+esc(draft.title||'Ujian Baru')+'</b><span class="b20-save" id="saveState">✓ Tersimpan otomatis</span></div><button class="b20-btn outline" id="pv">Preview</button></div><nav class="b20-steps">'+[['info','1. Informasi'],['questions','2. Soal'],['settings','3. Pengaturan'],['preview','4. Preview']].map(function(x){return '<button class="b20-step '+(step===x[0]?'active':'')+'" data-step="'+x[0]+'">'+x[1]+'</button>'}).join('')+'</nav></header>'}
function render(){app.innerHTML=head()+'<div class="b20-shell"><main class="b20-main">'+content()+'</main>'+side()+'</div>';bind()}
function content(){if(step==='info')return info();if(step==='questions')return questions();if(step==='settings')return settings();return preview()}
function info(){return '<section class="b20-card"><h2>Informasi Ujian</h2><p class="summary">Tentukan identitas, peserta, dan jadwal ujian.</p><div class="b20-grid2"><div class="b20-field"><label>Nama Ujian</label><input id="title" class="b20-input" value="'+esc(draft.title)+'" placeholder="Penilaian Harian Matematika"></div><div class="b20-field"><label>Mata Pelajaran</label><input id="subject" class="b20-input" value="'+esc(draft.subject)+'" placeholder="Matematika"></div></div><div class="b20-field"><label>Kelas Peserta</label><div class="b20-chips">'+classes.map(function(c){return '<label class="b20-chip"><input class="cls" type="checkbox" value="'+esc(c.id)+'" '+(draft.classes.indexOf(c.id)>=0?'checked':'')+'><span>'+esc(c.name||c.id)+'</span></label>'}).join('')+'</div></div><div class="b20-grid3"><div class="b20-field"><label>Mulai</label><input id="start" class="b20-input" type="datetime-local" value="'+esc(draft.startAt)+'"></div><div class="b20-field"><label>Selesai</label><input id="end" class="b20-input" type="datetime-local" value="'+esc(draft.endAt)+'"></div><div class="b20-field"><label>PIN (opsional)</label><input id="pin" class="b20-input" value="'+esc(draft.pin)+'"></div></div><div class="b20-row"><span class="grow"></span><button class="b20-btn primary" id="next">Simpan & Lanjut →</button></div></section>'}
function qcard(q,i){var ans='';if(q.type==='multiple_choice'||q.type==='multi_select')ans=q.options.map(function(o,j){var ck=q.type==='multiple_choice'?q.correctIndex===j:q.correctIndexes.indexOf(j)>=0;return '<div class="b20-opt"><input class="correct" type="'+(q.type==='multiple_choice'?'radio':'checkbox')+'" name="c'+q.id+'" value="'+j+'" '+(ck?'checked':'')+'><span>'+String.fromCharCode(65+j)+'</span><input class="b20-input opt" data-i="'+j+'" value="'+esc(o)+'" placeholder="Pilihan"><button class="delopt" data-i="'+j+'">×</button></div>'}).join('')+'<button class="b20-btn outline addopt">+ Pilihan</button>';else if(q.type==='true_false')ans='<div class="b20-field"><label>Jawaban benar</label><select class="b20-select answer"><option value="true" '+(q.answer==='true'?'selected':'')+'>Benar</option><option value="false" '+(q.answer==='false'?'selected':'')+'>Salah</option></select></div>';else if(q.type==='short_answer')ans='<div class="b20-field"><label>Jawaban yang diterima</label><input class="b20-input answer" value="'+esc(q.answer)+'"></div>';else ans='<p class="summary">Uraian dinilai manual.</p>';return '<article class="b20-card b20-q" id="q'+i+'"><div class="b20-qhead"><b class="b20-qnum">Soal '+(i+1)+'</b><span class="grow"></span><select class="b20-select b20-qtype type"><option value="multiple_choice">Pilihan Ganda</option><option value="multi_select">Multi Jawaban</option><option value="true_false">Benar / Salah</option><option value="short_answer">Isian Singkat</option><option value="essay">Uraian</option></select></div><textarea class="b20-textarea text" placeholder="Tuliskan pertanyaan...">'+esc(q.question)+'</textarea><div class="b20-grid2" style="margin-top:8px"><div class="b20-field"><label>Gambar (URL, opsional)</label><input class="b20-input image" value="'+esc(q.imageUrl)+'"></div><div class="b20-field"><label>Bobot</label><input class="b20-input points" type="number" min=".1" step=".1" value="'+q.points+'"></div></div>'+ans+'<div class="b20-qfoot"><label><input class="req" type="checkbox" '+(q.required?'checked':'')+'> Wajib</label><span class="grow"></span><button class="b20-btn outline dup">Duplikat</button><button class="b20-btn outline up">↑</button><button class="b20-btn outline down">↓</button><button class="b20-btn danger del">Hapus</button></div></article>'}
function questions(){return draft.questions.map(qcard).join('')+'<div class="b20-toolbar"><button class="b20-btn outline" id="add">+ Soal</button><button class="b20-btn outline" id="bank">📚 Bank Soal</button><button class="b20-btn primary publish" id="set">Pengaturan →</button></div>'}
function settings(){return '<section class="b20-card"><h2>Pengaturan Ujian</h2><div class="b20-checks"><label><input id="sq" type="checkbox" '+(draft.shuffleQuestions?'checked':'')+'> Acak soal</label><label><input id="so" type="checkbox" '+(draft.shuffleOptions?'checked':'')+'> Acak pilihan</label><label><input id="ab" type="checkbox" '+(draft.allowBack?'checked':'')+'> Boleh kembali</label><label><input id="ss" type="checkbox" '+(draft.showScore?'checked':'')+'> Tampilkan nilai</label></div><hr style="border:0;border-top:1px solid var(--line);margin:18px 0"><p class="summary"><b>Keamanan:</b> kunci jawaban disimpan di koleksi admin-only. Draft soal disimpan lokal agar tidak membebani kuota Firestore setiap ketikan.</p><div class="b20-row"><button class="b20-btn outline" id="bs">← Soal</button><span class="grow"></span><button class="b20-btn primary" id="tp">Preview →</button></div></section>'}
function preview(){return '<section class="b20-card"><h2>'+esc(draft.title||'Preview Ujian')+'</h2><p class="summary">'+esc(draft.subject)+' • '+draft.questions.length+' soal • '+points()+' poin</p></section>'+draft.questions.map(function(q,i){var o=(q.type==='multiple_choice'||q.type==='multi_select')?q.options.map(function(x){return '<div class="b20-preview-opt">○ '+esc(x||'Pilihan')+'</div>'}).join(''):(q.type==='true_false'?'<div class="b20-preview-opt">○ Benar</div><div class="b20-preview-opt">○ Salah</div>':'<div class="b20-preview-opt">Jawaban...</div>');return '<article class="b20-card b20-preview-q"><span class="summary">Soal '+(i+1)+' • '+q.points+' poin</span><h3>'+esc(q.question||'(Belum diisi)')+'</h3>'+o+'</article>'}).join('')+'<div class="b20-toolbar"><button class="b20-btn outline" id="bp">← Edit</button><button class="b20-btn primary publish" id="pub">Terbitkan Ujian</button></div>'}
function side(){if(step!=='questions')return '<aside class="b20-side"></aside>';var bad=draft.questions.filter(function(q){return !q.question}).length;return '<aside class="b20-side"><section class="b20-card"><b>Daftar Soal</b><div class="b20-navgrid">'+draft.questions.map(function(q,i){return '<button class="b20-navnum '+(!q.question?'warn':'')+'" data-nav="'+i+'">'+(i+1)+'</button>'}).join('')+'</div><p class="summary">'+draft.questions.length+' soal<br>'+points()+' poin'+(bad?'<br>⚠ '+bad+' belum lengkap':'<br>✓ Semua terisi')+'</p></section></aside>'}
function readInfo(){draft.title=document.getElementById('title').value.trim();draft.subject=document.getElementById('subject').value.trim();draft.startAt=document.getElementById('start').value;draft.endAt=document.getElementById('end').value;draft.pin=document.getElementById('pin').value.trim();draft.classes=[].slice.call(document.querySelectorAll('.cls:checked')).map(function(x){return x.value});save()}
function bind(){document.getElementById('back').onclick=function(){location.href='index.html'};document.getElementById('pv').onclick=function(){step='preview';render()};document.querySelectorAll('.b20-step').forEach(function(x){x.onclick=function(){step=x.dataset.step;render()}});
 if(step==='info'){['title','subject','start','end','pin'].forEach(function(id){document.getElementById(id).oninput=readInfo});document.querySelectorAll('.cls').forEach(function(x){x.onchange=readInfo});document.getElementById('next').onclick=function(){readInfo();step='questions';render()}}
 if(step==='questions')bindQ();
 if(step==='settings'){['sq','so','ab','ss'].forEach(function(id){document.getElementById(id).onchange=function(){draft.shuffleQuestions=document.getElementById('sq').checked;draft.shuffleOptions=document.getElementById('so').checked;draft.allowBack=document.getElementById('ab').checked;draft.showScore=document.getElementById('ss').checked;save()}});document.getElementById('bs').onclick=function(){step='questions';render()};document.getElementById('tp').onclick=function(){step='preview';render()}}
 if(step==='preview'){document.getElementById('bp').onclick=function(){step='questions';render()};document.getElementById('pub').onclick=publish}
 document.querySelectorAll('[data-nav]').forEach(function(x){x.onclick=function(){document.getElementById('q'+x.dataset.nav).scrollIntoView({behavior:'smooth',block:'center'})}})
}
